SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

IF OBJECT_ID('tempdb..#a') IS NOT NULL DROP TABLE #a;
SELECT id.IDENTITY_ID,
       p.PAT_NAME,
       CAST(pev.CONTACT_DATE AS DATE) AS CONTACT_DATE,
       pev.PAT_ENC_CSN_ID,
       pev.ENC_TYPE_C,
       det.NAME ENC_TYPE,
       ser.PROV_NAME VISIT_PROVIDER,
       pev.PCP_PROV_ID,
       dep.DEPARTMENT_NAME,
       eap.PROC_CODE AS LOS_PROC_CODE,
       eap.PROC_NAME,
       zas.NAME APPT_STATUS,
       SUBSTRING(dep.DEPT_ABBREVIATION, 3, 2) 'STATE',
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
           ELSE 'ERROR'
       END AS CITY,
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'MN' THEN 'MAIN LOCATION'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'DR' THEN 'D&R'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'KE' THEN 'KEENEN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'UC' THEN 'UNIVERSITY OF COLORADO'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'ON' THEN 'AUSTIN MAIN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'TW' THEN 'AUSTIN OTHER'
           ELSE 'ERROR'
       END AS 'SITE',
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'MD' THEN 'MEDICAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'DT' THEN 'DENTAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'CM' THEN 'CASE MANAGEMENT'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'RX' THEN 'PHARMACY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'AD' THEN 'BEHAVIORAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'PY' THEN 'BEHAVIORAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'BH' THEN 'BEHAVIORAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'MH' THEN 'BEHAVIORAL'
           ELSE 'ERROR'
       END AS 'LOS',
       (DATEDIFF(dd, pev.CONTACT_DATE, GETDATE()) + 1) - (DATEDIFF(wk, pev.CONTACT_DATE, GETDATE()) * 2)
       - (CASE WHEN DATENAME(dw, pev.CONTACT_DATE) = 'Sunday' THEN 1 ELSE 0 END) - (CASE WHEN DATENAME(dw, pev.CONTACT_DATE) = 'Saturday' THEN 1 ELSE 0 END) AS BUS_DAYS
INTO #a
FROM Clarity.dbo.PAT_ENC_VIEW pev
    LEFT JOIN Clarity.dbo.CLARITY_EAP eap ON pev.LOS_PRIME_PROC_ID = eap.PROC_ID
    INNER JOIN Clarity.dbo.PATIENT_VIEW p ON pev.PAT_ID = p.PAT_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON p.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON pev.VISIT_PROV_ID = ser.PROV_ID
    INNER JOIN Clarity.dbo.ZC_DISP_ENC_TYPE det ON pev.ENC_TYPE_C = det.DISP_ENC_TYPE_C
    INNER JOIN Clarity.dbo.CLARITY_DEP_VIEW dep ON pev.DEPARTMENT_ID = dep.DEPARTMENT_ID
    LEFT JOIN Clarity.dbo.ZC_APPT_STATUS zas ON zas.APPT_STATUS_C = pev.APPT_STATUS_C
WHERE pev.ENC_CLOSED_YN = 'N'
      /* Exlcuding Scans (OCHIN excludes these in their reports too), and Order Only (111) */
      AND pev.ENC_TYPE_C NOT IN ( '2006', '2010', '2008', '2001', '2011', '2004', '2003', '2009', '2005', '2007', '111' )
      AND (pev.APPT_STATUS_C IS NULL OR pev.APPT_STATUS_C IN ( 2, 6 ));

SELECT a.IDENTITY_ID,
       a.PAT_NAME,
       a.CONTACT_DATE,
       a.PAT_ENC_CSN_ID,
       a.ENC_TYPE_C,
       a.ENC_TYPE,
       a.VISIT_PROVIDER,
       a.DEPARTMENT_NAME,
       a.LOS,
       a.CITY,
       a.STATE,
       a.BUS_DAYS,
       a.PROC_NAME,
       CASE WHEN a.APPT_STATUS IS NULL THEN 'Non-scheduled'
           ELSE 'Scheduled'
       END AS SCHEDULED_YN
FROM #a a
WHERE a.BUS_DAYS > 2;
