SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

IF OBJECT_ID('tempdb..##survey_opt_outs') IS NOT NULL DROP TABLE ##survey_opt_outs;
SELECT IDENTITY_ID.IDENTITY_ID
INTO ##survey_opt_outs
FROM CLARITY.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID
WHERE IDENTITY_ID.IDENTITY_ID IN ( %s );

SELECT 1 FROM ##survey_opt_outs
