SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

SELECT pev.PAT_ID,
       pev.CONTACT_DATE LAST_OFFICE_VISIT,
       SUBSTRING(dep.DEPT_ABBREVIATION, 3, 2) 'STATE',
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
           ELSE SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2)
       END AS CITY,
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'MN' THEN 'MAIN LOCATION'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'DR' THEN 'D&R'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'KE' THEN 'KEENEN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'UC' THEN 'UNIVERSITY OF COLORADO'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'ON' THEN 'AUSTIN MAIN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 7, 2) = 'TW' THEN 'AUSTIN OTHER'
           ELSE 'ERROR'
       END AS 'SITE',
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'MD' THEN 'MEDICAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'DT' THEN 'DENTAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'CM' THEN 'CASE MANAGEMENT'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'RX' THEN 'PHARMACY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'AD' THEN 'BEHAVIORAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'PY' THEN 'BEHAVIORAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'BH' THEN 'BEHAVIORAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'MH' THEN 'BEHAVIORAL'
           ELSE 'ERROR'
       END AS 'LOS'
INTO #Attribution1
FROM Clarity.dbo.PAT_ENC_VIEW pev
    INNER JOIN Clarity.dbo.CLARITY_DEP_VIEW dep ON pev.DEPARTMENT_ID = dep.DEPARTMENT_ID
    INNER JOIN Clarity.dbo.CLARITY_TDL_TRAN_64_VIEW tdl ON pev.CHARGE_SLIP_NUMBER = tdl.CHARGE_SLIP_NUMBER --This join is only to pull out pts didn't have a billed visit

WHERE pev.CONTACT_DATE > DATEADD(MM, -12, GETDATE())
      AND pev.APPT_STATUS_C IN ( 2, 6 );

SELECT a1.PAT_ID,
       a1.STATE,
       a1.CITY,
       a1.SITE,
       a1.LOS,
       ROW_NUMBER() OVER (PARTITION BY a1.PAT_ID ORDER BY a1.LAST_OFFICE_VISIT DESC) AS ROW_NUM_DESC
INTO #Attribution2
FROM #Attribution1 a1
WHERE a1.LOS = 'DENTAL';

SELECT a2.PAT_ID,
       a2.STATE,
       a2.CITY,
       a2.SITE,
       a2.LOS
INTO #Attribution3
FROM #Attribution2 a2
    INNER JOIN Clarity.dbo.EPISODE_VIEW ev ON ev.PAT_LINK_ID = a2.PAT_ID
WHERE a2.ROW_NUM_DESC = 1
      AND ev.SUM_BLK_TYPE_ID = 45
      AND ev.STATUS_C = 1;

SELECT DISTINCT a3.PAT_ID
INTO #Attribution4
FROM #Attribution3 a3
    INNER JOIN Clarity.dbo.PAT_ENC_VIEW pev ON pev.PAT_ID = a3.PAT_ID
    INNER JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON pev.VISIT_PROV_ID = ser.PROV_ID
    INNER JOIN Clarity.dbo.CLARITY_TDL_TRAN_64_VIEW t64 ON pev.PAT_ENC_CSN_ID = t64.PAT_ENC_CSN_ID
WHERE t64.ORIG_SERVICE_DATE
      BETWEEN DATEADD(MONTH, -12, GETDATE()) AND GETDATE()
      AND ser.X_PROV_TYPE_C = 108;

SELECT pev.PAT_ID,
       MAX(CASE WHEN t64.CPT_CODE IN ( 'D1320', 'D1330', 'D0150', 'TT048' ) THEN 1
               ELSE 0 ---to assign a 1 where one of these procedures were done
           END) AS ORAL_HEALTH_ED
INTO #a
FROM Clarity.dbo.PAT_ENC_VIEW pev
    INNER JOIN #Attribution4 a4 ON a4.PAT_ID = pev.PAT_ID
    INNER JOIN Clarity.dbo.CLARITY_TDL_TRAN_64_VIEW t64 ON pev.PAT_ENC_CSN_ID = t64.PAT_ENC_CSN_ID --IJ since only looking for visits showing up on the billing side.
    LEFT JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON t64.PERFORMING_PROV_ID = ser.PROV_ID
WHERE t64.ORIG_SERVICE_DATE
      BETWEEN DATEADD(MONTH, -13, GETDATE()) AND GETDATE()
      AND t64.DETAIL_TYPE NOT IN ( 50, 51 )
GROUP BY pev.PAT_ID;

SELECT id.IDENTITY_ID,
       p.PAT_NAME,
       a.ORAL_HEALTH_ED,
       att.CITY,
       att.STATE
FROM #a a
    INNER JOIN Clarity.dbo.PATIENT_VIEW p ON a.PAT_ID = p.PAT_ID
    INNER JOIN Clarity.dbo.PATIENT_4 p4 ON p.PAT_ID = p4.PAT_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON a.PAT_ID = id.PAT_ID
    INNER JOIN #Attribution3 att ON a.PAT_ID = att.PAT_ID
WHERE p4.PAT_LIVING_STAT_C = 1;

DROP TABLE #a;
DROP TABLE #Attribution1;
DROP TABLE #Attribution2;
DROP TABLE #Attribution3;
DROP TABLE #Attribution4;
