/* ANL-MKE-SVR-200 */
SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

SELECT	DISTINCT
	id.IDENTITY_ID MRN
	,p.PAT_NAME
	,CASE
		WHEN pev.APPT_STATUS_C IN ( 2, 6 ) THEN 'KEPT'
		ELSE 'NOT KEPT'
	END AS APPT_STATUS
	,CASE
		WHEN zas.NAME = 'Arrived' THEN 'Completed'
		WHEN zas.NAME = 'Patient not cooperative' THEN 'No Show'
		WHEN zas.NAME = 'Late - Patient too late to be seen' THEN 'No Show'
		WHEN zas.NAME = 'Left without seen' THEN 'No Show'
		ELSE zas.NAME
	END AS 'APPT STATUS RAW'
	,CAST (pev.CONTACT_DATE AS DATE) 'VISIT DATE'
	,CASE
		WHEN ser.PROV_NAME = 	'ABUZAINEH DBLBK'	THEN	'ABUZAINEH, OMAR'
		WHEN ser.PROV_NAME = 	'AMORIN DBLBK'	THEN	'AMORIN, JORGE'
		WHEN ser.PROV_NAME LIKE	'BEARTLEIN DBLBK%'	THEN	'BAERTLEIN, ELISABETH'
		WHEN ser.PROV_NAME = 	'BISENIUS DBLBK'	THEN	'BISENIUS, STACEY'
		WHEN ser.PROV_NAME = 	'CARABALLO DBLBK'	THEN	'CARABALLO, AMARIS'
		WHEN ser.PROV_NAME = 	'CATTANEO, DBLBK'	THEN	'CATTANEO, KEVIN'
		WHEN ser.PROV_NAME = 	'CHAPLIN-BATHA, DBLBK'	THEN	'CHAPLIN-BATHA, TAMMY'
		WHEN ser.PROV_NAME = 	'CHON DBLBK'	THEN	'CHON, MICHAEL'
		WHEN ser.PROV_NAME = 	'DACOSTA DBLBK'	THEN	'DACOSTA, MICHELLE'
		WHEN ser.PROV_NAME = 	'DAUGHERTY, DBLBK'	THEN	'DAUGHERTY, CARLA'
		WHEN ser.PROV_NAME = 	'GREATENS DBLBK'	THEN	'GREATENS, SCOTT'
		WHEN ser.PROV_NAME = 	'GRODDY DBLBK'	THEN	'GRODDY, STEVEN'
		WHEN ser.PROV_NAME = 	'HARMON, DBLBK'	THEN	'HARMON, CHERYL'
		WHEN ser.PROV_NAME = 	'HOWLAND, DBLBK'	THEN	'HOWLAND, KATHRYN'
		WHEN ser.PROV_NAME = 	'LEMASTERS DBLBK'	THEN	'LEMASTERS, NICOLE'
		WHEN ser.PROV_NAME = 	'LINDBERG, DBLBK'	THEN	'LINDBERG, CHRISSY'
		WHEN ser.PROV_NAME = 	'MAGINE, DBLBK'	THEN	'MAGINE, TAMMY'
		WHEN ser.PROV_NAME = 	'MAINHURST DBLBK'	THEN	'MAINHURST, RONALD'
		WHEN ser.PROV_NAME = 	'MATHEW DBLBK'	THEN	'MATHEW, NATASHA'
		WHEN ser.PROV_NAME = 	'MENCHACA DBLBK'	THEN	'MENCHACA, ANTONIO'
		WHEN ser.PROV_NAME = 	'MORRIS DBLBK'	THEN	'MORRIS, ANDREA'
		WHEN ser.PROV_NAME = 	'MURRAY DBLBK'	THEN	'MURRAY, STEPHEN'
		WHEN ser.PROV_NAME = 	'RASCH DBLBK'	THEN	'RASCH, ALEX'
		WHEN ser.PROV_NAME = 	'REHORST DBLBK'	THEN	'REHORST, MARK'
		WHEN ser.PROV_NAME = 	'SANCHEZ DBLBK'	THEN	'SANCHEZ, MELBA'
		WHEN ser.PROV_NAME = 	'SHAH DBLBK'	THEN	'SHAH, MARIA'
		WHEN ser.PROV_NAME = 	'SHIRAH DBLBK'	THEN	'SHIRAH, JEFFREY'
		WHEN ser.PROV_NAME LIKE 	'TESSMANN DBLBK%'	THEN	'TESSMANN, DANIEL'
		WHEN ser.PROV_NAME = 	'WEAVER DBLBK'	THEN	'WEAVER, DELANEY'
		WHEN ser.PROV_NAME = 	'WILSDORF, DBLBK'	THEN	'WILSDORF, NICHOLAS'
		ELSE	ser.PROV_NAME 
	END AS 'VISIT PROVIDER'
	,ser.PROV_TYPE 'PROVIDER TYPE'
	,CASE
		WHEN ser.PROVIDER_TYPE_C IS NULL THEN 'Med - Other'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'AD' THEN 'BH - SUD'
		WHEN ser.PROVIDER_TYPE_C = '110' THEN 'BH - SUD'
		WHEN ser.PROVIDER_TYPE_C IN ( '136', '164' ) THEN 'BH - Psych'
		WHEN ser.PROVIDER_TYPE_C IN ( '117', '175', '134', '177', '10', '178' ) THEN 'BH - MH Therapy'
		WHEN ser.PROVIDER_TYPE_C IN ( '108' ) THEN 'Dental - Dentist'
		WHEN ser.PROVIDER_TYPE_C IN ( '119' ) THEN 'Dental - Hygienist'
		WHEN ser.PROVIDER_TYPE_C IN ( '137' ) THEN 'Dental - Other'
		WHEN ser.PROVIDER_TYPE_C IN ( '1', '9', '6', '113' ) THEN 'Med - Provider'
		WHEN ser.PROVIDER_TYPE_C IN ( '102', '173' ) THEN 'Med - Pharmacist'
		WHEN ser.PROVIDER_TYPE_C IN ( '104', '228' ) THEN 'Med - Dietitian/Nutritionist'
		WHEN ser.PROVIDER_TYPE_C IN ( '114', '200', '3', '201', '138' ) THEN 'Med - RN/MA'
		WHEN ser.PROVIDER_TYPE_C IN ( '158' ) THEN 'Med - Phlebotomist'
		WHEN ser.PROVIDER_TYPE_C IN ( '156', '125', '0', '222', '157' ) THEN 'Med - Other'
		ELSE ser.PROV_TYPE
	END AS 'Access Provider Groups'
	,ser.PROV_ID
	,CASE
		WHEN zpr.NAME IS NULL THEN 'Unknown'
		WHEN zpr.NAME = 'Patient Refused' THEN 'Unknown'
		WHEN zpr.NAME = 'Hispanic/Latino' THEN 'Unknown'
		ELSE zpr.NAME
	END AS RACE
	,COALESCE((DATEDIFF(m, p.BIRTH_DATE, GETDATE ()) / 12), 99) AGE
	,CASE
		WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 13 THEN '<13'
		WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 25 THEN '13-24'
		WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 45 THEN '25-44'
		WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 65 THEN '45-64'
		ELSE '65+'
	END AS 'AGE RANGE'
	,zs.NAME SEX
	,CASE
		WHEN h.[PATIENT TYPE] IS NOT NULL THEN h.[PATIENT TYPE]
		WHEN f.[PATIENT TYPE] IS NOT NULL THEN f.[PATIENT TYPE]
		ELSE 'Other'
	END AS 'PATIENT TYPE'
	,COALESCE (fsti.[EVER STI], 'N') 'EVER STI'
	,pev.APPT_PRC_ID
	,prc.PRC_NAME
	,COALESCE (sa.[iService County], zc.NAME) 'PATIENT COUNTY'
	,COALESCE (sa.ZIP_HX, p.ZIP) 'PATIENT ZIP CODE'
	,ser.PROV_TYPE
	,pev.PAT_ENC_CSN_ID
	,dep.DEPARTMENT_NAME
	,CASE
		WHEN zeg.NAME IS NULL THEN 'Unknown'
		WHEN zeg.NAME = 'Patient Refused' THEN 'Unknown'
		ELSE zeg.NAME
	END AS ETHNICITY
	,SUBSTRING (dep.DEPT_ABBREVIATION, 3, 2) AS STATE
	,CASE
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
		ELSE SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2)
	END AS CITY
	,CASE
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'MD' THEN 'MEDICAL'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'DT' THEN 'DENTAL'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'CM' THEN 'CASE MANAGEMENT'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'RX' THEN 'PHARMACY'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'AD' THEN 'BEHAVIORAL'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'PY' THEN 'BEHAVIORAL'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'BH' THEN 'BEHAVIORAL'
		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'MH' THEN 'BEHAVIORAL'
		ELSE 'ERROR'
	END AS 'LOS'
	,fpl.FPL
	,fpl.fpl_income FPL_INCOME
	,COALESCE (zgi.NAME, 'Not Recorded') 'GENDER IDENTITY'
	,COALESCE (sab.NAME, 'Not Recorded') 'SEX ASSGN AT BIRTH'
	,COALESCE (zso.NAME, 'Not Asked') 'SEXUAL ORIENTATION'
	,GETDATE () AS UPDATE_DTTM
	,p.EMPY_STATUS_C 'EMPLOYMENT STATUS CODE'
	,emps.NAME'EMPLOYMENT STATUS NAME'

FROM
	CLARITY.dbo.PAT_ENC_VIEW pev
	INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW dep ON dep.DEPARTMENT_ID = pev.DEPARTMENT_ID
	INNER JOIN CLARITY.dbo.PATIENT_VIEW p ON pev.PAT_ID = p.PAT_ID
	INNER JOIN CLARITY.dbo.PATIENT_4 p4 ON p4.PAT_ID = pev.PAT_ID
	LEFT JOIN CLARITY.dbo.ZC_EMPY_STATUS emps ON p.EMPY_STATUS_C = emps.EMPY_STATUS_C
	LEFT JOIN CLARITY.dbo.PAT_SEXUAL_ORIENTATION pso ON pso.PAT_ID = pev.PAT_ID
														AND pso.LINE = 1
	LEFT JOIN CLARITY.dbo.ZC_SEXUAL_ORIENTATION zso ON pso.SEXUAL_ORIENTATN_C = zso.SEXUAL_ORIENTATION_C
	LEFT JOIN CLARITY.dbo.ZC_ETHNIC_GROUP zeg ON zeg.ETHNIC_GROUP_C = p.ETHNIC_GROUP_C
	INNER JOIN CLARITY.dbo.IDENTITY_ID_VIEW id ON p.PAT_ID = id.PAT_ID
	LEFT JOIN CLARITY.dbo.PATIENT_RACE pr ON p.PAT_ID = pr.PAT_ID
											AND pr.LINE = 1
	LEFT JOIN CLARITY.dbo.ZC_PATIENT_RACE zpr ON pr.PATIENT_RACE_C = zpr.PATIENT_RACE_C
	LEFT JOIN CLARITY.dbo.ZC_SEX zs ON p.SEX_C = zs.RCPT_MEM_SEX_C
	LEFT JOIN CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW flagsti ON p.PAT_ID = flagsti.PATIENT_ID
															AND flagsti.PAT_FLAG_TYPE_C IN ( '640008', '640034' )
	LEFT JOIN CLARITY.dbo.CLARITY_SER_VIEW ser ON pev.VISIT_PROV_ID = ser.PROV_ID
	LEFT JOIN CLARITY.dbo.ZC_COUNTY zc ON p.COUNTY_C = zc.COUNTY_C
	LEFT JOIN CLARITY.dbo.ZC_APPT_STATUS zas ON pev.APPT_STATUS_C = zas.APPT_STATUS_C
	LEFT JOIN CLARITY.dbo.CLARITY_PRC prc ON pev.APPT_PRC_ID = prc.PRC_ID
	LEFT JOIN CLARITY.dbo.ZC_SEX_ASGN_AT_BIRTH sab ON sab.SEX_ASGN_AT_BIRTH_C = p4.SEX_ASGN_AT_BIRTH_C
	LEFT JOIN CLARITY.dbo.ZC_GENDER_IDENTITY zgi ON zgi.GENDER_IDENTITY_C = p4.GENDER_IDENTITY_C
	LEFT JOIN
	(
		SELECT
			fpl1.PAT_ID
			,MIN (fpl1.fpl_income) fpl_income
			,MIN (fpl1.fpl_percentage) FPL

		FROM
			CLARITY.dbo.X_FPL_MAX_VIEW fpl1

		GROUP BY
			fpl1.PAT_ID
	) fpl ON fpl.PAT_ID = pev.PAT_ID
	LEFT JOIN
	(
		SELECT
			flag.PATIENT_ID
			,CASE
						WHEN flag.PAT_FLAG_TYPE_C = '640005'
							AND flag.ACTIVE_C = 1 THEN 'PrEP'
						WHEN flag.PAT_FLAG_TYPE_C IN ( '640008', '640034' )
							AND flag.ACTIVE_C = 1 THEN 'STI'
						WHEN flag.PAT_FLAG_TYPE_C = '6400017'
							AND flag.ACTIVE_C = 1 THEN 'False Positive HIV Test'
						WHEN flag.PAT_FLAG_TYPE_C = '9800035'
							AND flag.ACTIVE_C = 1 THEN 'PEP'
						WHEN flag.PAT_FLAG_TYPE_C = '640007'
							AND flag.ACTIVE_C = 1 THEN 'AODA HIV-'
						WHEN flag.PAT_FLAG_TYPE_C = '640050'
							AND flag.ACTIVE_C = 1 THEN 'HEP C'
						
						ELSE 'Other'
					END
				 AS 'PATIENT TYPE'
			,ROW_NUMBER() OVER (PARTITION BY flag.PATIENT_ID ORDER BY flag.ACCT_NOTE_INSTANT DESC) AS ROW_NUM_DESC

		FROM
			CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW flag
		WHERE
			flag.PAT_FLAG_TYPE_C IN ( /*PrEP*/ '640005', /*False Pos*/ '640017', /*PEP*/ '9800035', /*STI*/ '640008' /*AODA HIV-*/, '640007', /*Other HIV-*/ '9800065', /*MPX as STI*/ '640034', '640050' )
			AND flag.ACTIVE_C = 1

	) f ON pev.PAT_ID = f.PATIENT_ID
			AND f.ROW_NUM_DESC = 1 --Most Recently set flag
	LEFT JOIN
	(
		SELECT	DISTINCT
			plv.PAT_ID
			,'HIV+' AS 'PATIENT TYPE'

		FROM
			CLARITY.dbo.PROBLEM_LIST_VIEW plv
			INNER JOIN CLARITY.dbo.CLARITY_EDG edg ON plv.DX_ID = edg.DX_ID
			INNER JOIN CLARITY.dbo.EDG_CURRENT_ICD10 icd10 ON edg.DX_ID = icd10.DX_ID

		WHERE
			icd10.CODE IN ( 'B20', 'Z21', 'B97.35' ) --HIV and Asymptomatic HIV
			AND plv.RESOLVED_DATE IS NULL --Active Dx
			AND plv.PROBLEM_STATUS_C = 1	--Active Dx
	) h ON h.PAT_ID = pev.PAT_ID
	LEFT JOIN
	(
		SELECT
			flagsti.PATIENT_ID
			,MAX (	CASE
						WHEN flagsti.PAT_FLAG_TYPE_C = '640008' THEN 'Y'
						ELSE NULL
					END
				) AS 'EVER STI'

		FROM
			CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW flagsti

		WHERE
			flagsti.PAT_FLAG_TYPE_C = '640008'
		GROUP BY
			flagsti.PATIENT_ID
	) fsti ON pev.PAT_ID = fsti.PATIENT_ID
	LEFT JOIN
	(
		SELECT	DISTINCT
			pev.PAT_ID
			,pev.CONTACT_DATE 'Treatment Plan Initiated'
			,pev.PAT_ENC_CSN_ID
			,zcx.NAME 'iService County'
				--,zsx.ABBR 'iService State' --Don't need this (or city) since those come from the Dept table
			,pax.ZIP_HX
			,ROW_NUMBER () OVER (PARTITION BY pev.PAT_ENC_CSN_ID ORDER BY pax.EFF_START_DATE ASC) AS ROW_NUM_ASC

		FROM
			CLARITY.dbo.PAT_ENC_VIEW pev
			LEFT JOIN CLARITY.dbo.PAT_ADDR_CHNG_HX pax ON pax.PAT_ID = pev.PAT_ID --Address at time of service
														AND pax.EFF_START_DATE <= pev.CONTACT_DATE
														AND
														(
															pax.EFF_END_DATE IS NULL
															OR	pax.EFF_END_DATE > pev.CONTACT_DATE
														)
			LEFT JOIN CLARITY.dbo.ZC_COUNTY zcx ON pax.COUNTY_HX_C = zcx.COUNTY_C
		--LEFT JOIN Clarity.dbo.ZC_STATE zsx ON pax.STATE_HX_C = zsx.STATE_C

		WHERE
			pev.APPT_STATUS_C IN ( 2, 4, 5, 6, 7, 12, 13, 16 )
			AND pev.CONTACT_DATE >= '1/1/2018'
	) sa ON sa.PAT_ENC_CSN_ID = pev.PAT_ENC_CSN_ID
			AND sa.ROW_NUM_ASC = 1
WHERE
	pev.APPT_STATUS_C IN ( 2, 4, 5, 6, 7, 12, 13, 16 )
	AND id.IDENTITY_ID NOT IN ( '640000142', '640006736', '640013794', '640004280', '640000238', '640004716', '640004717', '640032696' ) --Very young and old pts who never completed a visit
	AND pev.CONTACT_DATE >= '1/1/2018'
	AND
	(
		dep.DEPARTMENT_NAME = 'XXXVH AUS DENTAL'
		OR	dep.DEPARTMENT_NAME NOT LIKE 'XXX%'
	)

--UNION

--SELECT	DISTINCT
--	id.IDENTITY_ID 'MRN'
--	,p.PAT_NAME
--	,'KEPT' APPT_STATUS
--	,'Pharmacy Contacts Do Not Have Appt Status' 'APPT STATUS RAW'
--	,CAST (pev.CONTACT_DATE AS DATE) 'VISIT DATE'
--	,COALESCE (ser.PROV_NAME, 'Pharamcy Staff') 'VISIT PROVIDER'
--	,COALESCE (ser.PROV_TYPE, 'Pharmacy Staff') 'PROVIDER TYPE'
--	,'Retail Pharmacy' 'Access Provider Groups'
--	,ser.PROV_ID
--	,CASE
--			WHEN zpr.NAME IS NULL THEN 'Unknown'
--			WHEN zpr.NAME = 'Patient Refused' THEN 'Unknown'
--			WHEN zpr.NAME = 'Hispanic/Latino' THEN 'Unknown'
--			ELSE zpr.NAME
--		END AS RACE
--	,COALESCE((DATEDIFF(m, p.BIRTH_DATE, GETDATE ()) / 12), 99) AGE
--	,CASE
--			WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 13 THEN '<13'
--			WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 25 THEN '13-24'
--			WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 45 THEN '25-44'
--			WHEN (DATEDIFF (m, p.BIRTH_DATE, GETDATE ()) / 12) < 65 THEN '45-64'
--			ELSE '65+'
--		END AS 'AGE RANGE'
--	,zs.NAME SEX
--	,CASE
--			WHEN h.[PATIENT TYPE] IS NOT NULL THEN h.[PATIENT TYPE]
--			WHEN f.[PATIENT TYPE] IS NOT NULL THEN f.[PATIENT TYPE]
--			ELSE 'Other'
--		END AS 'PATIENT TYPE'
--	,COALESCE (fsti.[EVER STI], 'N') 'EVER STI'
--	,pev.APPT_PRC_ID
--	,'Pharmacy Contact' PRC_NAME
--	,COALESCE (sa.[iService County], zc.NAME) 'PATIENT COUNTY'
--	,COALESCE (sa.ZIP_HX, p.ZIP) 'PATIENT ZIP CODE'
--	,COALESCE (ser.PROV_TYPE, 'Pharmacy Staff') 'PROV_TYPE'
--	,pev.PAT_ENC_CSN_ID
--	,dep.DEPARTMENT_NAME
--	,CASE
--		WHEN zeg.NAME IS NULL THEN 'Unknown'
--		WHEN zeg.NAME = 'Patient Refused' THEN 'Unknown'
--		ELSE zeg.NAME
--	END AS ETHNICITY
--	,SUBSTRING (dep.DEPT_ABBREVIATION, 3, 2) AS STATE
--	,CASE
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
--		ELSE SUBSTRING (dep.DEPT_ABBREVIATION, 5, 2)
--	END AS CITY
--	,CASE
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'MD' THEN 'MEDICAL'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'DT' THEN 'DENTAL'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'CM' THEN 'CASE MANAGEMENT'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'RX' THEN 'PHARMACY'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'AD' THEN 'BEHAVIORAL'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'PY' THEN 'BEHAVIORAL'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'BH' THEN 'BEHAVIORAL'
--		WHEN SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'MH' THEN 'BEHAVIORAL'
--		ELSE 'ERROR'
--	END AS 'LOS'
--	,fpl.FPL
--	,fpl.fpl_income FPL_INCOME
--	,COALESCE (zgi.NAME, 'Not Recorded') 'GENDER IDENTITY'
--	,COALESCE (sab.NAME, 'Not Recorded') 'SEX ASSGN AT BIRTH'
--	,COALESCE (zso.NAME, 'Not Asked') 'SEXUAL ORIENTATION'
--	,GETDATE () AS UPDATE_DTTM

--FROM
--	CLARITY.dbo.PAT_ENC_VIEW pev
--	INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW dep ON dep.DEPARTMENT_ID = pev.DEPARTMENT_ID
--	INNER JOIN CLARITY.dbo.PATIENT_VIEW p ON pev.PAT_ID = p.PAT_ID
--	INNER JOIN CLARITY.dbo.PATIENT_4 p4 ON p4.PAT_ID = pev.PAT_ID
--	LEFT JOIN CLARITY.dbo.PAT_SEXUAL_ORIENTATION pso ON pso.PAT_ID = pev.PAT_ID
--														AND pso.LINE = 1
--	LEFT JOIN CLARITY.dbo.ZC_SEXUAL_ORIENTATION zso ON pso.SEXUAL_ORIENTATN_C = zso.SEXUAL_ORIENTATION_C
--	LEFT JOIN CLARITY.dbo.ZC_ETHNIC_GROUP zeg ON zeg.ETHNIC_GROUP_C = p.ETHNIC_GROUP_C
--	INNER JOIN CLARITY.dbo.IDENTITY_ID_VIEW id ON p.PAT_ID = id.PAT_ID
--	LEFT JOIN CLARITY.dbo.PATIENT_RACE pr ON p.PAT_ID = pr.PAT_ID
--											AND pr.LINE = 1
--	LEFT JOIN CLARITY.dbo.ZC_PATIENT_RACE zpr ON pr.PATIENT_RACE_C = zpr.PATIENT_RACE_C
--	LEFT JOIN CLARITY.dbo.ZC_SEX zs ON p.SEX_C = zs.RCPT_MEM_SEX_C
--	LEFT JOIN CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW flagsti ON p.PAT_ID = flagsti.PATIENT_ID
--															AND flagsti.PAT_FLAG_TYPE_C IN ( '640008', '640034' )
--	LEFT JOIN CLARITY.dbo.CLARITY_SER_VIEW ser ON pev.VISIT_PROV_ID = ser.PROV_ID
--	LEFT JOIN CLARITY.dbo.ZC_COUNTY zc ON p.COUNTY_C = zc.COUNTY_C
--	LEFT JOIN CLARITY.dbo.ZC_APPT_STATUS zas ON pev.APPT_STATUS_C = zas.APPT_STATUS_C
--	LEFT JOIN CLARITY.dbo.CLARITY_PRC prc ON pev.APPT_PRC_ID = prc.PRC_ID
--	LEFT JOIN CLARITY.dbo.ZC_SEX_ASGN_AT_BIRTH sab ON sab.SEX_ASGN_AT_BIRTH_C = p4.SEX_ASGN_AT_BIRTH_C
--	LEFT JOIN CLARITY.dbo.ZC_GENDER_IDENTITY zgi ON zgi.GENDER_IDENTITY_C = p4.GENDER_IDENTITY_C
--	LEFT JOIN
--	(
--		SELECT
--			fpl1.PAT_ID
--			,MIN (fpl1.fpl_income) fpl_income
--			,MIN (fpl1.fpl_percentage) FPL
--		FROM
--			CLARITY.dbo.X_FPL_MAX_VIEW fpl1
--		GROUP BY
--			fpl1.PAT_ID
--	) fpl ON fpl.PAT_ID = pev.PAT_ID
--	LEFT JOIN
--	(
--		SELECT
--			flag.PATIENT_ID
--			,MIN (	CASE
--						WHEN flag.PAT_FLAG_TYPE_C = '640005'
--							AND flag.ACTIVE_C = 1 THEN 'PrEP'
--						WHEN flag.PAT_FLAG_TYPE_C IN ( '640008', '640034' )
--							AND flag.ACTIVE_C = 1 THEN 'STI'
--						WHEN flag.PAT_FLAG_TYPE_C = '6400017'
--							AND flag.ACTIVE_C = 1 THEN 'False Positive HIV Test'
--						WHEN flag.PAT_FLAG_TYPE_C = '9800035'
--							AND flag.ACTIVE_C = 1 THEN 'PEP'
--						WHEN flag.PAT_FLAG_TYPE_C = '640007'
--							AND flag.ACTIVE_C = 1 THEN 'AODA HIV-'
--						ELSE 'Other'
--					END
--				) AS 'PATIENT TYPE'

--		FROM
--			CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW flag

--		WHERE
--			flag.PAT_FLAG_TYPE_C IN ( /*PrEP*/ '640005', /*False Pos*/ '640017', /*PEP*/ '9800035', /*STI*/ '640008' /*AODA HIV-*/, '640007', /*Other HIV-*/ '9800065', /*MPX as STI*/ '640034' )
--			AND flag.ACTIVE_C = 1

--		GROUP BY
--			flag.PATIENT_ID
--	) f ON pev.PAT_ID = f.PATIENT_ID
--	LEFT JOIN
--	(
--		SELECT	DISTINCT
--			plv.PAT_ID
--			,'HIV+' AS 'PATIENT TYPE'

--		FROM
--			CLARITY.dbo.PROBLEM_LIST_VIEW plv
--			INNER JOIN CLARITY.dbo.CLARITY_EDG edg ON plv.DX_ID = edg.DX_ID
--			INNER JOIN CLARITY.dbo.EDG_CURRENT_ICD10 icd10 ON edg.DX_ID = icd10.DX_ID

--		WHERE
--			icd10.CODE IN ( 'B20', 'Z21', 'B97.35' ) --HIV and Asymptomatic HIV
--			AND plv.RESOLVED_DATE IS NULL --Active Dx
--			AND plv.PROBLEM_STATUS_C = 1	--Active Dx
--	) h ON h.PAT_ID = pev.PAT_ID
--	LEFT JOIN
--	(
--		SELECT
--			flagsti.PATIENT_ID
--			,MAX (	CASE
--						WHEN flagsti.PAT_FLAG_TYPE_C = '640008' THEN 'Y'
--						ELSE NULL
--					END
--			) AS 'EVER STI'
--		FROM
--			CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW flagsti
--		WHERE
--			flagsti.PAT_FLAG_TYPE_C = '640008'
--		GROUP BY
--			flagsti.PATIENT_ID
--	) fsti ON pev.PAT_ID = fsti.PATIENT_ID
--	LEFT JOIN
--	(
--		SELECT	DISTINCT
--			pev.PAT_ID
--			,pev.CONTACT_DATE 'Treatment Plan Initiated'
--			,pev.PAT_ENC_CSN_ID
--			,zcx.NAME 'iService County'
--				--,zsx.ABBR 'iService State' --Don't need this (or city) since those come from the Dept table
--			,pax.ZIP_HX
--			,ROW_NUMBER () OVER (PARTITION BY pev.PAT_ENC_CSN_ID ORDER BY pax.EFF_START_DATE ASC) AS ROW_NUM_ASC

--		FROM
--			CLARITY.dbo.PAT_ENC_VIEW pev
--			LEFT JOIN CLARITY.dbo.PAT_ADDR_CHNG_HX pax ON pax.PAT_ID = pev.PAT_ID --Address at time of service
--														AND pax.EFF_START_DATE <= pev.CONTACT_DATE
--														AND
--														(
--															pax.EFF_END_DATE IS NULL
--															OR	pax.EFF_END_DATE > pev.CONTACT_DATE
--														)
--			LEFT JOIN CLARITY.dbo.ZC_COUNTY zcx ON pax.COUNTY_HX_C = zcx.COUNTY_C
--		--LEFT JOIN Clarity.dbo.ZC_STATE zsx ON pax.STATE_HX_C = zsx.STATE_C

--		WHERE
--			pev.APPT_STATUS_C IN ( 2, 4, 5, 6, 7, 12, 13, 16 )
--			AND pev.CONTACT_DATE >= '1/1/2018'
--	) sa ON sa.PAT_ENC_CSN_ID = pev.PAT_ENC_CSN_ID
--			AND sa.ROW_NUM_ASC = 1
--WHERE
--	id.IDENTITY_ID NOT IN ( '640000142', '640006736', '640013794', '640004280', '640000238', '640004716', '640004717', '640032696' ) --Very young and old pts who never completed a visit
--	AND pev.CONTACT_DATE >= '1/1/2018'
--	AND SUBSTRING (dep.DEPT_ABBREVIATION, 9, 2) = 'RX'	-- Pharmacy

;