/** 
 * ANL-MKE-SVR-100
 */

SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

SELECT pev.PAT_ID,
       pev.CONTACT_DATE LAST_OFFICE_VISIT,
       dep.STATE,
       dep.CITY,
       dep.SITE,
       dep.SERVICE_TYPE,
       dep.SERVICE_LINE AS LOS,
       dep.SUB_SERVICE_LINE
INTO #Attribution1
FROM Clarity.dbo.PAT_ENC_VIEW pev
    LEFT JOIN ANALYTICS.TRANSFORM.DepartmentMapping dep ON dep.DEPARTMENT_ID = pev.DEPARTMENT_ID
WHERE pev.CONTACT_DATE > DATEADD(MONTH, -48, GETDATE())
      AND pev.APPT_STATUS_C IN ( 2, 6 );

SELECT a1.PAT_ID,
       a1.STATE,
       a1.CITY,
       a1.SITE,
       a1.LOS,
       a1.SERVICE_TYPE,
       a1.SUB_SERVICE_LINE,
       ROW_NUMBER() OVER (PARTITION BY a1.PAT_ID ORDER BY a1.LAST_OFFICE_VISIT DESC) AS ROW_NUM_DESC
INTO #Attribution2
FROM #Attribution1 a1
WHERE a1.LOS = 'MEDICAL';

SELECT a2.PAT_ID, a2.LOS, a2.CITY, a2.STATE, a2.SERVICE_TYPE, a2.SUB_SERVICE_LINE INTO #Attribution3 FROM #Attribution2 a2 WHERE a2.ROW_NUM_DESC = 1;

SELECT id.IDENTITY_ID,
       p.PAT_ID,
       p.PAT_NAME,
       a3.CITY,
       a3.STATE,
       a3.LOS,
       a3.SERVICE_TYPE,
       a3.SUB_SERVICE_LINE,
       MAX(CASE --To pick 'Y' for people who have been in and out of the cohort
               WHEN flag.ACTIVE_C = 1 THEN 'Y'
               ELSE 'N'
           END) AS ACTIVE_TO_COHORT,
       MAX(flag.ACCT_NOTE_INSTANT) COHORT_ENROLL_DATE,
       ser.EXTERNAL_NAME PCP
INTO #pop
FROM Clarity.dbo.PATIENT_VIEW p
    LEFT JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON p.CUR_PCP_PROV_ID = ser.PROV_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON p.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.PATIENT_FYI_FLAGS_VIEW flag ON p.PAT_ID = flag.PATIENT_ID
    INNER JOIN #Attribution3 a3 ON a3.PAT_ID = p.PAT_ID
WHERE flag.PAT_FLAG_TYPE_C = '640012'
GROUP BY id.IDENTITY_ID,
         p.PAT_ID,
         p.PAT_NAME,
         a3.CITY,
         a3.STATE,
         a3.LOS,
         a3.SERVICE_TYPE,
         a3.SUB_SERVICE_LINE,
         ser.EXTERNAL_NAME;

SELECT --to get last BP
id.IDENTITY_ID,
p.PAT_ID,
pev.CONTACT_DATE,
pev.BP_SYSTOLIC,
pev.BP_DIASTOLIC,
ROW_NUMBER() OVER (PARTITION BY id.IDENTITY_ID ORDER BY pev.APPT_TIME DESC) AS ROW_NUM_DESC
INTO #lb
FROM #pop pop
    INNER JOIN Clarity.dbo.PATIENT_VIEW p ON p.PAT_ID = pop.PAT_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON p.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.PAT_ENC_VIEW pev ON p.PAT_ID = pev.PAT_ID
WHERE pev.BP_SYSTOLIC IS NOT NULL
      AND pev.CONTACT_DATE >= CAST(pop.COHORT_ENROLL_DATE AS DATE);

SELECT * INTO #a FROM #lb lb WHERE lb.ROW_NUM_DESC = 1;

SELECT --To get first BP
pop.PAT_ID,
pev.BP_SYSTOLIC FIRST_DIASTOLIC,
pev.BP_DIASTOLIC FIRST_SYSTOLIC,
pev.CONTACT_DATE SECOND_LAST_READING,
ROW_NUMBER() OVER (PARTITION BY pop.PAT_ID ORDER BY pev.APPT_TIME DESC) AS ROW_NUM_DESC
INTO #d
FROM #pop pop
    INNER JOIN Clarity.dbo.PAT_ENC_VIEW pev ON pev.PAT_ID = pop.PAT_ID
WHERE pev.BP_SYSTOLIC IS NOT NULL
      AND pev.CONTACT_DATE <= CAST(pop.COHORT_ENROLL_DATE AS DATE);

SELECT d.PAT_ID, d.FIRST_DIASTOLIC, d.FIRST_SYSTOLIC, d.SECOND_LAST_READING INTO #e FROM #d d WHERE d.ROW_NUM_DESC = 1;

SELECT pop.IDENTITY_ID,
       pop.PCP,
       pop.PAT_ID,
       pop.PAT_NAME,
       CASE WHEN a.CONTACT_DATE IS NULL THEN e.SECOND_LAST_READING
           ELSE a.CONTACT_DATE
       END AS LAST_READING,
       CASE WHEN a.BP_SYSTOLIC IS NULL THEN e.FIRST_SYSTOLIC
           ELSE a.BP_SYSTOLIC
       END AS LATEST_SYSTOLIC,
       CASE WHEN a.BP_DIASTOLIC IS NULL THEN e.FIRST_DIASTOLIC
           ELSE a.BP_DIASTOLIC
       END AS LATEST_DIASTOLIC,
       e.SECOND_LAST_READING,
       e.FIRST_DIASTOLIC,
       e.FIRST_SYSTOLIC,
       pop.CITY,
       pop.STATE,
       pop.LOS,
       pop.SERVICE_TYPE,
       pop.SUB_SERVICE_LINE,
       pop.ACTIVE_TO_COHORT,
       pop.COHORT_ENROLL_DATE
INTO #b
FROM #pop pop
    LEFT JOIN #a a ON a.PAT_ID = pop.PAT_ID
    LEFT JOIN #e e ON e.PAT_ID = pop.PAT_ID;

SELECT b.IDENTITY_ID,
       b.PAT_ID,
       b.PCP,
       b.PAT_NAME,
       b.LAST_READING,
       b.SECOND_LAST_READING FIRST_READING,
       b.LATEST_SYSTOLIC,
       b.LATEST_DIASTOLIC,
       b.FIRST_SYSTOLIC,
       b.FIRST_DIASTOLIC,
       CASE WHEN b.LATEST_SYSTOLIC < 140
                 AND b.LATEST_DIASTOLIC < 90 THEN 0
           ELSE 1
       END AS CURR_HIGH_BP,
       CASE WHEN b.FIRST_SYSTOLIC < 140
                 AND b.FIRST_DIASTOLIC < 90 THEN 0
           ELSE 1
       END AS PREVIOUS_HIGH_BP,
       b.CITY,
       b.STATE,
       b.LOS,
       b.SERVICE_TYPE,
       b.SUB_SERVICE_LINE,
       b.ACTIVE_TO_COHORT,
       b.COHORT_ENROLL_DATE
INTO #c
FROM #b b;

SELECT c.IDENTITY_ID MRN,
       c.PAT_ID,
       c.PCP,
       c.PAT_NAME PATIENT,
       CAST(c.LAST_READING AS DATE) AS LAST_READING,
       CAST(c.FIRST_READING AS DATE) AS SECOND_LAST_READING,
       c.LATEST_SYSTOLIC,
       c.LATEST_DIASTOLIC,
       CONVERT(VARCHAR(3), c.LATEST_SYSTOLIC) + '/' + CONVERT(VARCHAR(3), c.LATEST_DIASTOLIC) CURRENT_BP,
       c.FIRST_SYSTOLIC,
       c.FIRST_DIASTOLIC,
       CONVERT(VARCHAR(3), c.FIRST_SYSTOLIC) + '/' + CONVERT(VARCHAR(3), c.FIRST_DIASTOLIC) ORIG_BP,
       c.PREVIOUS_HIGH_BP ORIG_HIGH_BP,
       c.CURR_HIGH_BP,
       CASE WHEN c.CURR_HIGH_BP = 1
                 AND c.PREVIOUS_HIGH_BP = 1 THEN 'NO CHANGE UNCONTROLLED'
           WHEN c.CURR_HIGH_BP = 0
                AND c.PREVIOUS_HIGH_BP = 0 THEN 'NO CHANGE CONTROLLED'
           WHEN c.CURR_HIGH_BP = 1
                AND c.PREVIOUS_HIGH_BP = 0 THEN 'NEWLY UNCONTROLLED'
           WHEN c.CURR_HIGH_BP = 0
                AND c.PREVIOUS_HIGH_BP = 1 THEN 'NEWLY CONTROLLED'
       END AS STATUS,
       CASE WHEN c.CURR_HIGH_BP = 1 THEN 'UNMET'
           ELSE 'MET'
       END AS MET_YN,
       c.CITY,
       c.STATE,
       c.LOS,
       c.SERVICE_TYPE,
       c.SUB_SERVICE_LINE,
       c.ACTIVE_TO_COHORT,
       c.COHORT_ENROLL_DATE
FROM #c c;

DROP TABLE #Attribution1;
DROP TABLE #Attribution2;
DROP TABLE #Attribution3;
DROP TABLE #a;
DROP TABLE #b;
DROP TABLE #c;
DROP TABLE #d;
DROP TABLE #e;
DROP TABLE #pop;
DROP TABLE #lb;