/**
 * ANL-MKE-SVR-100
 **/

SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

SELECT id.IDENTITY_ID MRN,
       p.PAT_NAME PATIENT,
       CAST(pev.CONTACT_DATE AS DATE) AS CONTACT_DATE,
       CAST(t64.ORIG_SERVICE_DATE AS DATE) AS 'PROCEDURE DATE',
       t64.CPT_CODE 'CPT CODE',
       eap.PROC_NAME 'PROCEDURE',
       ser.PROV_NAME 'PERFORMING PROVIDER',
       SUBSTRING(dep.DEPT_ABBREVIATION, 3, 2) 'STATE',
       CASE WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
           ELSE SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2)
       END AS CITY,dep.SPECIALTY,dep.DEPARTMENT_ID,
       ROW_NUMBER() OVER (PARTITION BY pev.PAT_ID, t64.CPT_CODE
ORDER BY t64.ORIG_SERVICE_DATE DESC) AS ROW_NUM_DESC
INTO #a
FROM Clarity.dbo.CLARITY_TDL_TRAN_64_VIEW t64
    INNER JOIN Clarity.dbo.PAT_ENC_VIEW pev ON t64.PAT_ENC_CSN_ID = pev.PAT_ENC_CSN_ID
    INNER JOIN Clarity.dbo.CLARITY_DEP_VIEW dep ON dep.DEPARTMENT_ID = pev.DEPARTMENT_ID
    LEFT JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON t64.PERFORMING_PROV_ID = ser.PROV_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON pev.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.PATIENT_VIEW p ON p.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.CLARITY_EAP eap ON eap.PROC_ID = t64.PROC_ID
--LEFT JOIN Clarity.dbo.ZC_FINANCIAL_CLASS zfc ON t64.CUR_FIN_CLASS = zfc.FINANCIAL_CLASS
WHERE t64.DETAIL_TYPE = 1
      --AND t64.CPT_CODE IN ( 'D5120', 'D5140' )
     and dep.SPECIALTY='Dental' AND pev.CONTACT_DATE > '1/1/2021';

SELECT a.MRN,
       a.PATIENT,
       a.CONTACT_DATE,
       a.[PROCEDURE DATE],
       a.[CPT CODE],
       a.[PROCEDURE],
       a.[PERFORMING PROVIDER],
       a.STATE,
       a.CITY,
       a.SPECIALTY,
       a.DEPARTMENT_ID
FROM #a a
WHERE a.ROW_NUM_DESC = 1;

DROP TABLE #a;
