/**
 * ANL-MKE-SVR-100
 **/

SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

SELECT id.IDENTITY_ID MRN,
       p.PAT_NAME PATIENT,
       CAST(pev.CONTACT_DATE AS DATE) AS CONTACT_DATE,
       CAST(t64.ORIG_SERVICE_DATE AS DATE) AS 'PROCEDURE DATE',
       t64.CPT_CODE 'CPT CODE',
       eap.PROC_NAME 'PROCEDURE',
       ser.PROV_NAME 'PERFORMING PROVIDER',
       dep.STATE,
       dep.CITY,
       dep.SERVICE_TYPE,
       dep.SERVICE_LINE,
       dep.SUB_SERVICE_LINE,
       dep2.SPECIALTY,dep.DEPARTMENT_ID,
       ROW_NUMBER() OVER (PARTITION BY pev.PAT_ID, t64.CPT_CODE
ORDER BY t64.ORIG_SERVICE_DATE DESC) AS ROW_NUM_DESC
INTO #a
FROM Clarity.dbo.CLARITY_TDL_TRAN_64_VIEW t64
    INNER JOIN Clarity.dbo.PAT_ENC_VIEW pev ON t64.PAT_ENC_CSN_ID = pev.PAT_ENC_CSN_ID
    INNER JOIN Clarity.dbo.CLARITY_DEP_VIEW dep2 ON dep2.DEPARTMENT_ID = pev.DEPARTMENT_ID
    LEFT JOIN ANALYTICS.TRANSFORM.DepartmentMapping dep ON dep.DEPARTMENT_ID = pev.DEPARTMENT_ID
    LEFT JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON t64.PERFORMING_PROV_ID = ser.PROV_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON pev.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.PATIENT_VIEW p ON p.PAT_ID = id.PAT_ID
    INNER JOIN Clarity.dbo.CLARITY_EAP eap ON eap.PROC_ID = t64.PROC_ID
--LEFT JOIN Clarity.dbo.ZC_FINANCIAL_CLASS zfc ON t64.CUR_FIN_CLASS = zfc.FINANCIAL_CLASS
WHERE t64.DETAIL_TYPE = 1
      --AND t64.CPT_CODE IN ( 'D5120', 'D5140' )
     and dep2.SPECIALTY='Dental' AND pev.CONTACT_DATE > '1/1/2021';

SELECT a.MRN,
       a.PATIENT,
       a.CONTACT_DATE,
       a.[PROCEDURE DATE],
       a.[CPT CODE],
       a.[PROCEDURE],
       a.[PERFORMING PROVIDER],
       a.STATE,
       a.CITY,
       a.SERVICE_TYPE,
       a.SERVICE_LINE,
       a.SUB_SERVICE_LINE,
       a.SPECIALTY,
       a.DEPARTMENT_ID
FROM #a a
WHERE a.ROW_NUM_DESC = 1;

DROP TABLE #a;
