SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

IF OBJECT_ID('tempdb..#latest_visit_info') IS NOT NULL DROP TABLE #latest_visit_info;
SELECT PAT_ENC.PAT_ID,
       PAT_ENC.PAT_ENC_CSN_ID,
       CAST(PAT_ENC.CONTACT_DATE AS DATE) AS LAST_VISIT_DATE,
       SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) AS STATE,
       CASE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2)
           WHEN 'MK' THEN 'MILWAUKEE'
           WHEN 'KN' THEN 'KENOSHA'
           WHEN 'GB' THEN 'GREEN BAY'
           WHEN 'WS' THEN 'WAUSAU'
           WHEN 'AP' THEN 'APPLETON'
           WHEN 'EC' THEN 'EAU CLAIRE'
           WHEN 'LC' THEN 'LACROSSE'
           WHEN 'MD' THEN 'MADISON'
           WHEN 'BL' THEN 'BELOIT'
           WHEN 'BI' THEN 'BILLING'
           WHEN 'SL' THEN 'ST LOUIS'
           WHEN 'DN' THEN 'DENVER'
           WHEN 'AS' THEN 'AUSTIN'
           WHEN 'KC' THEN 'KANSAS CITY'
           WHEN 'CG' THEN 'CHICAGO'
           ELSE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2)
       END AS CITY,
       CASE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 9, 2)
           WHEN 'MD' THEN 'MEDICAL'
           WHEN 'DT' THEN 'DENTAL'
           ELSE 'ERROR'
       END AS DEPARTMENT_NAME,
       CLARITY_SER.PROV_NAME AS PCP,
       ROW_NUMBER() OVER (PARTITION BY PAT_ENC.PAT_ID ORDER BY PAT_ENC.CONTACT_DATE DESC) AS ROW_NUM_DESC
INTO #latest_visit_info
FROM CLARITY.dbo.PAT_ENC_VIEW AS PAT_ENC
    INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID
    INNER JOIN CLARITY.dbo.CLARITY_SER_VIEW AS CLARITY_SER ON PAT_ENC.PCP_PROV_ID = CLARITY_SER.PROV_ID -- ensures a visit with a VH provider
WHERE PAT_ENC.APPT_STATUS_C IN ( 2, 6 )
      AND SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 9, 2) = 'MD';


IF OBJECT_ID('tempdb..#hiv_labs') IS NOT NULL DROP TABLE #hiv_labs;
WITH
    cd4 AS (
        SELECT DISTINCT CLARITY_COMPONENT.COMPONENT_ID
        FROM CLARITY.dbo.CLARITY_COMPONENT AS CLARITY_COMPONENT
        WHERE CLARITY_COMPONENT.COMMON_NAME IN ( 'CD4 ABSOLUTE', 'CD3+ CD4+ ABSOLUTE', 'CD4 (ABSOLUTE)' ) ---https://loinc.org/24467-3/
              AND CLARITY_COMPONENT.NAME <> 'ABSOLUTE CD4, HISTORICAL'
    ),
    cd4_info AS (
        SELECT 1 AS CD4_LAB_INDICATOR,
               ORDER_PROC.PAT_ID,
               ORDER_RESULTS.PAT_ENC_CSN_ID,
               ORDER_RESULTS.ORD_VALUE AS CD4_LAB_VALUE,
               CAST(ORDER_RESULTS.RESULT_DATE AS DATE) AS CD4_RESULT_DT,
               ROW_NUMBER() OVER (PARTITION BY ORDER_PROC.PAT_ENC_CSN_ID,
                                               ORDER_RESULTS.PAT_ENC_CSN_ID
                                  ORDER BY ORDER_RESULTS.RESULT_DATE DESC) AS ROW_NUM_DESC
        FROM CLARITY.dbo.ORDER_PROC_VIEW AS ORDER_PROC
            INNER JOIN CLARITY.dbo.ORDER_RESULTS_VIEW AS ORDER_RESULTS ON ORDER_PROC.ORDER_PROC_ID = ORDER_RESULTS.ORDER_PROC_ID
        WHERE ORDER_RESULTS.COMPONENT_ID IN ( SELECT cd4.COMPONENT_ID FROM cd4 )
              AND ORDER_RESULTS.ORD_VALUE NOT IN ( 'Delete', 'See comment' )
              AND ORDER_RESULTS.LAB_STATUS_C = 5 -- Edited Result - FINAL
    ),
    vls AS (
        SELECT DISTINCT CLARITY_COMPONENT.COMPONENT_ID
        FROM CLARITY.dbo.CLARITY_COMPONENT AS CLARITY_COMPONENT
        WHERE CLARITY_COMPONENT.COMMON_NAME = 'HIV VIRAL LOAD'
    ),
    vls_info AS (
        SELECT 1 AS VLS_LAB_INDICATOR,
               ORDER_PROC.PAT_ID,
               ORDER_RESULTS.PAT_ENC_CSN_ID,
               ORDER_RESULTS.ORD_VALUE AS VIRAL_LOAD_RNA_VALUE,
               CASE WHEN ORDER_RESULTS.ORD_NUM_VALUE <> 9999999
                         AND ORDER_RESULTS.ORD_NUM_VALUE < 200 THEN 'SUPPRESSED'
                   WHEN ORDER_RESULTS.ORD_NUM_VALUE <> 9999999
                        AND ORDER_RESULTS.ORD_NUM_VALUE > 199 THEN 'UNSUPPRESSED'
                   WHEN ORDER_RESULTS.ORD_VALUE LIKE '>%' THEN 'UNSUPPRESSED'
                   ELSE 'SUPPRESSED'
               END AS VIRAL_LOAD_SUPPRESSION_STATUS_CATC,
               CASE WHEN ORDER_RESULTS.ORD_NUM_VALUE <> 9999999 THEN 'DETECTABLE'
                   WHEN ORDER_RESULTS.ORD_NUM_VALUE <> 9999999
                        AND ORDER_RESULTS.ORD_VALUE LIKE '>%' THEN 'DETECTABLE'
                   ELSE 'UNDETECTABLE'
               END AS VIRAL_LOAD_DETECTION_STATUS_CATC,
               CAST(ORDER_RESULTS.RESULT_DATE AS DATE) AS VLS_RESULT_DT,
               ROW_NUMBER() OVER (PARTITION BY ORDER_PROC.PAT_ENC_CSN_ID,
                                               ORDER_RESULTS.PAT_ENC_CSN_ID
                                  ORDER BY ORDER_RESULTS.RESULT_DATE DESC) AS ROW_NUM_DESC
        FROM CLARITY.dbo.ORDER_PROC_VIEW AS ORDER_PROC
            INNER JOIN CLARITY.dbo.ORDER_RESULTS_VIEW AS ORDER_RESULTS ON ORDER_PROC.ORDER_PROC_ID = ORDER_RESULTS.ORDER_PROC_ID
        WHERE ORDER_RESULTS.COMPONENT_ID IN ( SELECT vls.COMPONENT_ID FROM vls )
              AND ORDER_RESULTS.ORD_VALUE NOT IN ( 'Delete', 'See comment' )
              AND ORDER_RESULTS.LAB_STATUS_C = 5 -- Edited Result - FINAL
    ),
    all_labs AS (
        SELECT vls_info.PAT_ID,
               vls_info.VLS_LAB_INDICATOR,
               vls_info.VIRAL_LOAD_RNA_VALUE,
               vls_info.VIRAL_LOAD_SUPPRESSION_STATUS_CATC,
               vls_info.VIRAL_LOAD_DETECTION_STATUS_CATC,
               vls_info.VLS_RESULT_DT,
               cd4_info.CD4_LAB_INDICATOR,
               cd4_info.CD4_LAB_VALUE,
               cd4_info.CD4_RESULT_DT,
               ROW_NUMBER() OVER (PARTITION BY vls_info.PAT_ID
                                  ORDER BY COALESCE(vls_info.VLS_RESULT_DT, cd4_info.CD4_RESULT_DT) DESC) AS ROW_NUM_DESC
        FROM vls_info
            LEFT JOIN cd4_info ON vls_info.PAT_ENC_CSN_ID = cd4_info.PAT_ENC_CSN_ID
                                  AND vls_info.ROW_NUM_DESC = cd4_info.ROW_NUM_DESC
        GROUP BY vls_info.PAT_ID,
                 vls_info.VLS_LAB_INDICATOR,
                 vls_info.VIRAL_LOAD_RNA_VALUE,
                 vls_info.VIRAL_LOAD_SUPPRESSION_STATUS_CATC,
                 vls_info.VIRAL_LOAD_DETECTION_STATUS_CATC,
                 vls_info.VLS_RESULT_DT,
                 cd4_info.CD4_LAB_INDICATOR,
                 cd4_info.CD4_LAB_VALUE,
                 cd4_info.CD4_RESULT_DT
    )
SELECT all_labs.PAT_ID,
       all_labs.VLS_LAB_INDICATOR,
       all_labs.VIRAL_LOAD_RNA_VALUE,
       all_labs.VIRAL_LOAD_SUPPRESSION_STATUS_CATC,
       all_labs.VIRAL_LOAD_DETECTION_STATUS_CATC,
       all_labs.VLS_RESULT_DT,
       all_labs.CD4_LAB_INDICATOR,
       all_labs.CD4_LAB_VALUE,
       all_labs.CD4_RESULT_DT
INTO #hiv_labs
FROM all_labs
WHERE all_labs.ROW_NUM_DESC = 1;


SELECT PATIENT.PAT_NAME AS PATIENT_NAME,
       (DATEDIFF(MONTH, PATIENT.BIRTH_DATE, GETDATE()) / 12) AS PATIENT_AGE,
       IDENTITY_ID.IDENTITY_ID AS MRN,
       #latest_visit_info.LAST_VISIT_DATE AS LAST_MEDICAL_VISIT_DATE,
       #latest_visit_info.STATE,
       #latest_visit_info.CITY,
	   #latest_visit_info.PCP,
       CASE WHEN #hiv_labs.VLS_LAB_INDICATOR IS NOT NULL THEN 'MET'
           ELSE 'NOT MET'
       END AS HAS_VLS_LAB,
       CASE WHEN #hiv_labs.CD4_LAB_INDICATOR IS NOT NULL THEN 'MET'
           ELSE 'NOT MET'
       END AS HAS_CD4_LAB,
       #hiv_labs.VIRAL_LOAD_RNA_VALUE,
       #hiv_labs.VIRAL_LOAD_SUPPRESSION_STATUS_CATC,
       #hiv_labs.VIRAL_LOAD_DETECTION_STATUS_CATC,
       #hiv_labs.VLS_RESULT_DT,
       #hiv_labs.CD4_LAB_VALUE,
       #hiv_labs.CD4_RESULT_DT,
       CURRENT_TIMESTAMP AS UPDATE_DTTM
FROM #latest_visit_info
    LEFT JOIN #hiv_labs ON #latest_visit_info.PAT_ID = #hiv_labs.PAT_ID
    INNER JOIN CLARITY.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID ON #latest_visit_info.PAT_ID = IDENTITY_ID.PAT_ID
    INNER JOIN CLARITY.dbo.PATIENT_VIEW AS PATIENT ON IDENTITY_ID.PAT_ID = PATIENT.PAT_ID
WHERE #latest_visit_info.ROW_NUM_DESC = 1;
