SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

IF OBJECT_ID('tempdb..##excluded_mrns') IS NOT NULL DROP TABLE ##excluded_mrns;
SELECT IDENTITY_ID.IDENTITY_ID
INTO ##excluded_mrns
FROM CLARITY.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID
WHERE IDENTITY_ID.IDENTITY_ID IN ( %s );

SELECT 1 FROM ##excluded_mrns
