/*
Project:            Clinic Administered Drugs - Tableau Data Source
Query:              clinic_administered_drugs.sql
Description:        Clinic injectables based on NDC list. Requested by Todd Miller.

Author:             Benzon Salazar (Benzon.Salazar@viventhealth.org)
System:             javelin.ochin.org
Dependencies:       None.
Inclusion Criteria: NDC List:  60793-701-02
                               60793-702-04
                               60793-702-10
                               49702-253-15
                               49702-240-15
                               49702-264-23
Exclusion Criteria: None.
Timeframe:          2019-09-01 - Today
Comments:           Tableau Workbook will be created by JoAnn Berk.
                    Originally, this came from the Bicillin Use Workbook, but 
                    Todd Miller would like to expand that workbook include the 
                    rest of the NDC codes listed in the Inclusion Criteria.

				Limit to Cabenauva and Bicillin - per Todd 8/16/2024
				
				Per JoAnn 11/19/2024
				Can you expand your inclusion criteria to include any of the following?
					CPT Code: J2315
					NDC: 65757030001
					Item/CPT Description: includes 'Naltrexone'

*/

SET ANSI_WARNINGS OFF;
SET NOCOUNT ON;


SELECT 
	IDENTITY_ID.IDENTITY_ID AS MRN,
    PATIENT.PAT_NAME AS PATIENT_NAME,
	CAST(PATIENT.BIRTH_DATE AS DATE) AS DOB,
	CAST(PAT_ENC.CONTACT_DATE AS DATE) AS VISIT_DATE,
	eap2.PROC_NAME AS MEDICATION_NAME,
	CAST(ORDER_MED.ORDERING_DATE AS DATE) AS MEDICATION_ORDERED_DATE,
	MAR_ADMIN_INFO.TAKEN_TIME AS MEDICATION_TAKEN_TIME,
	CLARITY_EMP.NAME AS MEDICATION_ADMINISTERED_BY,
	ORDER_MED.HV_DISCRETE_DOSE AS UNITS,
	MAX(RX_NDC.NDC_CODE) AS NDC_CODE,
	eap2.PROC_NAME 'Charge Description',
	CLARITY_TDL_TRAN_64.CPT_CODE,
	CLARITY_SER.PROV_NAME AS VISIT_PROVIDER_NAME,
	SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) AS STATE,
	CASE WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
        WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
        ELSE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2)
    END AS CITY,
    CASE WHEN ZC_FINANCIAL_CLASS.NAME IS NULL THEN 'Self-Pay'
        WHEN ZC_FINANCIAL_CLASS.NAME = 'Blue Cross' THEN 'Commercial'
        ELSE ZC_FINANCIAL_CLASS.NAME
    END AS FINANCIAL_CLASS,
    COALESCE(CLARITY_EPM.PAYOR_NAME, 'UNINSURED') AS PAYOR,
    X_VISIT_DATE.TOTAL_CHG_AMOUNT AS TOTAL_CHARGE_AMOUNT,
	SUM(CLARITY_TDL_TRAN_64.AMOUNT) 'CPT Charge Amount'


FROM 
	CLARITY.dbo.ORDER_MED_VIEW AS ORDER_MED
    INNER JOIN CLARITY.dbo.CLARITY_MEDICATION AS CLARITY_MEDICATION ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID
    INNER JOIN CLARITY.dbo.MAR_ADMIN_INFO_VIEW AS MAR_ADMIN_INFO ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID
    INNER JOIN Clarity.dbo.CLARITY_EMP_VIEW AS CLARITY_EMP ON MAR_ADMIN_INFO.USER_ID = CLARITY_EMP.USER_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID ON ORDER_MED.PAT_ID = IDENTITY_ID.PAT_ID
    INNER JOIN Clarity.dbo.PATIENT_VIEW AS PATIENT ON ORDER_MED.PAT_ID = PATIENT.PAT_ID
    INNER JOIN Clarity.dbo.PAT_ENC_VIEW AS PAT_ENC ON ORDER_MED.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID
    INNER JOIN CLARITY.dbo.CLARITY_SER_VIEW AS CLARITY_SER ON PAT_ENC.VISIT_PROV_ID = CLARITY_SER.PROV_ID
    INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID
    LEFT JOIN CLARITY.dbo.CLARITY_UCL_VIEW AS CLARITY_UCL ON ORDER_MED.ORDER_MED_ID = CLARITY_UCL.ORDER_ID
    LEFT JOIN CLARITY.dbo.RX_NDC AS RX_NDC ON CLARITY_UCL.NDC_CODE_ID = RX_NDC.NDC_ID
    LEFT JOIN Clarity.dbo.CLARITY_TDL_TRAN_64_VIEW AS CLARITY_TDL_TRAN_64 ON PAT_ENC.CHARGE_SLIP_NUMBER = CLARITY_TDL_TRAN_64.CHARGE_SLIP_NUMBER
					AND CLARITY_TDL_TRAN_64.DETAIL_TYPE IN (1, 10)
					--AND CLARITY_TDL_TRAN_64.CPT_CODE <> 'J0696'
					--AND CLARITY_TDL_TRAN_64.CPT_CODE NOT LIKE '8%'
	LEFT JOIN Clarity.dbo.CLARITY_EAP eap2 ON CLARITY_TDL_TRAN_64.PROC_ID = eap2.PROC_ID
    LEFT JOIN CLARITY.dbo.X_VISIT_DATE_VIEW AS X_VISIT_DATE ON X_VISIT_DATE.CHARGE_SLIP_NUMBER = PAT_ENC.CHARGE_SLIP_NUMBER
    LEFT JOIN CLARITY.dbo.ZC_FINANCIAL_CLASS AS ZC_FINANCIAL_CLASS ON X_VISIT_DATE.ORIGINAL_FIN_CLASS = ZC_FINANCIAL_CLASS.FINANCIAL_CLASS
    LEFT JOIN CLARITY.dbo.CLARITY_EPM AS CLARITY_EPM ON X_VISIT_DATE.ORIGINAL_PAYOR_ID = CLARITY_EPM.PAYOR_ID

WHERE 
	PAT_ENC.CONTACT_DATE > '2019-08-31'
	--AND (CLARITY_MEDICATION.NAME LIKE '%PENICILLIN%'
	--	OR CLARITY_MEDICATION.NAME LIKE '%CABOTEGRAVIR%'
	--	OR CLARITY_MEDICATION.NAME LIKE '%BICILLIN%'
	--	OR CLARITY_TDL_TRAN_64.CPT_CODE = 'J2315' --Mitch updating 11/19/2024 Per JoAnn
	--	OR RX_NDC.RAW_11_DIGIT_NDC= '65757030001'--Mitch updating 11/19/2024 Per JoAnn
	--	OR eap2.PROC_NAME LIKE '%Naltrexone%'--Mitch updating 11/19/2024 Per JoAnn
	--	)
--      AND RX_NDC.NDC_CODE IN ( '60793-701-02', '60793-702-04', '60793-702-10', '49702-253-15', '49702-240-15', '49702-264-23' )

GROUP BY 
	CAST(PATIENT.BIRTH_DATE AS DATE),
	CAST(PAT_ENC.CONTACT_DATE AS DATE),
	CAST(ORDER_MED.ORDERING_DATE AS DATE),
	ZC_FINANCIAL_CLASS.NAME,
	CLARITY_DEP.DEPT_ABBREVIATION,
	COALESCE(CLARITY_EPM.PAYOR_NAME, 'UNINSURED'),
	IDENTITY_ID.IDENTITY_ID,
	PATIENT.PAT_NAME,
	CLARITY_MEDICATION.NAME,
	MAR_ADMIN_INFO.TAKEN_TIME,
	CLARITY_EMP.NAME,
	ORDER_MED.HV_DISCRETE_DOSE,
	CLARITY_TDL_TRAN_64.CPT_CODE,
	CLARITY_SER.PROV_NAME,
	X_VISIT_DATE.TOTAL_CHG_AMOUNT,
	eap2.PROC_NAME

		 
ORDER BY 
	MRN,
	VISIT_DATE,
	MEDICATION_ORDERED_DATE,
	MEDICATION_TAKEN_TIME
	
;


