SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

IF OBJECT_ID('tempdb..#target_patients') IS NOT NULL 
DROP TABLE #target_patients;

SELECT PATIENT.PAT_NAME,
       IDENTITY_ID.IDENTITY_ID AS MRN,
       CAST(PAT_ENC.CONTACT_DATE AS DATE) AS VISIT_DATE,
       ZC_APPT_STATUS.NAME AS APPT_STATUS,
       CASE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2)
           WHEN 'CO' THEN 'Colorado'
           WHEN 'TX' THEN 'Texas'
           WHEN 'IL' THEN 'Illinois'
           WHEN 'WI' THEN 'Wisconsin'
           WHEN 'MO' THEN 'Missouri'
           ELSE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2)
       END AS STATE,
       CASE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2)
           WHEN 'MK' THEN 'MILWAUKEE'
           WHEN 'KN' THEN 'KENOSHA'
           WHEN 'GB' THEN 'GREEN BAY'
           WHEN 'WS' THEN 'WAUSAU'
           WHEN 'AP' THEN 'APPLETON'
           WHEN 'EC' THEN 'EAU CLAIRE'
           WHEN 'LC' THEN 'LACROSSE'
           WHEN 'MD' THEN 'MADISON'
           WHEN 'BL' THEN 'BELOIT'
           WHEN 'BI' THEN 'BILLING'
           WHEN 'SL' THEN 'ST LOUIS'
           WHEN 'DN' THEN 'DENVER'
           WHEN 'AS' THEN 'AUSTIN'
           WHEN 'KC' THEN 'KANSAS CITY'
           WHEN 'CG' THEN 'CHICAGO'
           ELSE 'ERROR'
       END AS CITY,
       CASE WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 9, 2) = 'MD' THEN 'MEDICAL'
           WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 9, 2) = 'DT' THEN 'DENTAL'
           WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 9, 2) IN ( 'MH', 'BH', 'PY' ) THEN 'BEHAVIORAL'
           ELSE 'ERROR'
       END AS LOS,
       CASE WHEN PAT_ENC.APPT_STATUS_C IN ( 4, 5, 7, 13 ) THEN 'YES'
           ELSE 'NO'
       END AS NO_SHOWS_GRP
	   ,CASE
			WHEN f_bh.PAT_FLAG_TYPE_C IS NOT NULL THEN 'Yes'
			ELSE 'No'
		END AS 'No Show Flag - BH'
		,CASE
			WHEN f_dn.PAT_FLAG_TYPE_C IS NOT NULL THEN 'Yes'
			ELSE 'No'
		END AS 'No Show Flag - Dental'
		,CASE
			WHEN f_md.PAT_FLAG_TYPE_C IS NOT NULL THEN 'Yes'
			ELSE 'No'
		END AS 'No Show Flag - Medical'


INTO #target_patients

FROM 
	CLARITY.dbo.PAT_ENC_VIEW AS PAT_ENC
    INNER JOIN CLARITY.dbo.PATIENT_VIEW AS PATIENT ON PAT_ENC.PAT_ID = PATIENT.PAT_ID
    INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID
    INNER JOIN CLARITY.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID ON PATIENT.PAT_ID = IDENTITY_ID.PAT_ID
    INNER JOIN CLARITY.dbo.ZC_APPT_STATUS AS ZC_APPT_STATUS ON PAT_ENC.APPT_STATUS_C = ZC_APPT_STATUS.APPT_STATUS_C
    INNER JOIN CLARITY.dbo.CLARITY_SER_VIEW AS CLARITY_SER ON PAT_ENC.VISIT_PROV_ID = CLARITY_SER.PROV_ID
	LEFT JOIN Clarity.dbo.PATIENT_FYI_FLAGS_VIEW f_bh ON f_bh.PATIENT_ID = PATIENT.PAT_ID
							AND f_bh.PAT_FLAG_TYPE_C = '640049' --BH No Show
							AND f_bh.ACTIVE_C = 1
	LEFT JOIN Clarity.dbo.PATIENT_FYI_FLAGS_VIEW f_dn ON f_dn.PATIENT_ID = PATIENT.PAT_ID
							AND f_dn.PAT_FLAG_TYPE_C = '640048' --Dental No Show
							AND f_dn.ACTIVE_C = 1
	LEFT JOIN Clarity.dbo.PATIENT_FYI_FLAGS_VIEW f_md ON f_md.PATIENT_ID = PATIENT.PAT_ID
							AND f_md.PAT_FLAG_TYPE_C = '640047' --Med NO Show
							AND f_md.ACTIVE_C = 1

WHERE 
	SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 9, 2) IN ( 'MH', 'BH', 'PY', 'MD', 'DT' )
    AND PAT_ENC.CONTACT_DATE > DATEADD(MONTH, -12, GETDATE())
	AND PAT_ENC.CONTACT_DATE >= '8/1/2024' --Per Adam, data start on 8/1/2024
    AND CLARITY_SER.PROVIDER_TYPE_C IN ( '119', '108', '239', '117', '177', '227', '134', '9', '1', '6', '164', '136', '175', '113' )
	
;


SELECT 
	tp.PAT_NAME,
	tp.MRN,
	tp.VISIT_DATE,
	tp.APPT_STATUS,
	tp.STATE,
	tp.CITY,
	tp.LOS,
	tp.NO_SHOWS_GRP
	,MAX(tp.[No Show Flag - Medical]) 'No_Show_Flag_Medical'
	,MAX(tp.[No Show Flag - BH]) 'No_Show_Flag_BH'
	,MAX(tp.[No Show Flag - Dental]) 'No_Show_Flag_Dental'

FROM 
	#target_patients tp

GROUP BY 
	tp.PAT_NAME,
	tp.MRN,
	tp.VISIT_DATE,
	tp.APPT_STATUS,
	tp.STATE,
	tp.CITY,
	tp.LOS,
	tp.NO_SHOWS_GRP

ORDER BY 
	tp.PAT_NAME,
    tp.LOS,
    tp.VISIT_DATE
	
;

DROP TABLE #target_patients