

SET NOCOUNT ON
;
SET ANSI_WARNINGS OFF
;

/*

**********************************************************************************************

 *****   GENERAL INFO   *****

 Object Name:	dental_prophy_1
 Create Date:	1/15/2025
 Created By:	ViventHealth\MScoggins
 System:		ANL-MKE-SVR-200
 Requested By:	Adam C.

 Description:
 

 *****  Modification History *****

 Change Date:		Changed By:			Change Description:
 ------------		-------------		---------------------------------------------------
 1/15/2025			Mitch				Updating the numerator to use visit where gum depth was probed, instead of billing codes. Per Adam and Dr. Menchacha
 9/19/2025		    Hari				Added "Visit Provider Name" column

**********************************************************************************************

 */

IF OBJECT_ID ('tempdb..#excl') IS NOT NULL
	DROP TABLE #excl
	;

SELECT --get pts with the endentulouos dx code
	plv.PAT_ID
	,MAX (5) 'K Code'
	,NULL 'D5110'
	,NULL 'D5120'

INTO #excl

FROM
	CLARITY.dbo.PROBLEM_LIST_VIEW AS plv
	INNER JOIN CLARITY.dbo.CLARITY_EDG AS CLARITY_EDG ON plv.DX_ID = CLARITY_EDG.DX_ID
	INNER JOIN CLARITY.dbo.EDG_CURRENT_ICD10 AS EDG_CURRENT_ICD10 ON CLARITY_EDG.DX_ID = EDG_CURRENT_ICD10.DX_ID

WHERE
	EDG_CURRENT_ICD10.CODE = 'K08.109' --"Complete loss of teeth, unspecified cause, unspecified class"
	AND plv.RESOLVED_DATE IS NULL --Active Dx
	AND plv.PROBLEM_STATUS_C = 1	--Active Dx

GROUP BY
	plv.PAT_ID

UNION

SELECT
	tdl.PAT_ID
	,NULL 'K Code'
	,MAX (1) 'D5110'
	,NULL 'D5120'

FROM
	CLARITY.dbo.CLARITY_TDL_TRAN_64_VIEW tdl

WHERE
	tdl.CPT_CODE = 'D5110'
	AND tdl.DETAIL_TYPE NOT IN ( 50, 51 )

GROUP BY
	tdl.PAT_ID

UNION

SELECT
	tdl.PAT_ID
	,NULL 'K COde'
	,NULL 'D5110'
	,MAX (1) 'D5120'

FROM
	CLARITY.dbo.CLARITY_TDL_TRAN_64_VIEW tdl

WHERE
	tdl.CPT_CODE = 'D5120'
	AND tdl.DETAIL_TYPE NOT IN ( 50, 51 )

GROUP BY
	tdl.PAT_ID

;

IF OBJECT_ID ('tempdb..#exclusion') IS NOT NULL
	DROP TABLE #exclusion
	;

SELECT
	e.PAT_ID
	,COALESCE (MAX (e.[K Code]), 0) 'K Code'
	,COALESCE (MAX (e.D5110), 0) 'D5110'
	,COALESCE (MAX (e.D5120), 0) 'D5120'
	,COALESCE (MAX (e.[K Code]), 0) + COALESCE (MAX (e.D5110), 0) + COALESCE (MAX (e.D5120), 0) 'Total Exclusion Score'

INTO #exclusion

FROM
	#excl e

GROUP BY
	e.PAT_ID

HAVING
	COALESCE (MAX (e.[K Code]), 0) + COALESCE (MAX (e.D5110), 0) + COALESCE (MAX (e.D5120), 0) > 1

;

IF OBJECT_ID ('tempdb..#Attribution1') IS NOT NULL
	DROP TABLE #Attribution1
	;
SELECT
	PAT_ENC.PAT_ID
	,PAT_ENC.CONTACT_DATE LAST_OFFICE_VISIT
	,SUBSTRING (CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) AS STATE
	,CASE SUBSTRING (CLARITY_DEP.DEPT_ABBREVIATION, 5, 2)
		WHEN 'MK' THEN 'MILWAUKEE'
		WHEN 'KN' THEN 'KENOSHA'
		WHEN 'GB' THEN 'GREEN BAY'
		WHEN 'WS' THEN 'WAUSAU'
		WHEN 'AP' THEN 'APPLETON'
		WHEN 'EC' THEN 'EAU CLAIRE'
		WHEN 'LC' THEN 'LACROSSE'
		WHEN 'MD' THEN 'MADISON'
		WHEN 'BL' THEN 'BELOIT'
		WHEN 'BI' THEN 'BILLING'
		WHEN 'SL' THEN 'ST LOUIS'
		WHEN 'DN' THEN 'DENVER'
		WHEN 'AS' THEN 'AUSTIN'
		WHEN 'KC' THEN 'KANSAS CITY'
		WHEN 'CG' THEN 'CHICAGO'
		ELSE SUBSTRING (CLARITY_DEP.DEPT_ABBREVIATION, 5, 2)
	END AS CITY
	,CASE SUBSTRING (CLARITY_DEP.DEPT_ABBREVIATION, 7, 2)
		WHEN 'MN' THEN 'MAIN LOCATION'
		WHEN 'DR' THEN 'D&R'
		WHEN 'KE' THEN 'KEENEN'
		WHEN 'UC' THEN 'UNIVERSITY OF COLORADO'
		WHEN 'ON' THEN 'AUSTIN MAIN'
		WHEN 'TW' THEN 'AUSTIN OTHER'
		ELSE 'ERROR'
	END AS SITE
	,CASE SUBSTRING (CLARITY_DEP.DEPT_ABBREVIATION, 9, 2)
		WHEN 'MD' THEN 'MEDICAL'
		WHEN 'DT' THEN 'DENTAL'
		WHEN 'CM' THEN 'CASE MANAGEMENT'
		WHEN 'RX' THEN 'PHARMACY'
		WHEN 'AD' THEN 'BEHAVIORAL'
		WHEN 'PY' THEN 'BEHAVIORAL'
		WHEN 'BH' THEN 'BEHAVIORAL'
		WHEN 'MH' THEN 'BEHAVIORAL'
		ELSE 'ERROR'
	END AS LOS
	,CLARITY_SER.PROV_TYPE AS VISIT_PROVIDER_TYPE

INTO #Attribution1

FROM
	CLARITY.dbo.PAT_ENC_VIEW AS PAT_ENC
	INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON CLARITY_DEP.DEPARTMENT_ID = PAT_ENC.DEPARTMENT_ID
	INNER JOIN CLARITY.dbo.CLARITY_SER_VIEW AS CLARITY_SER ON PAT_ENC.VISIT_PROV_ID = CLARITY_SER.PROV_ID

WHERE
	PAT_ENC.CONTACT_DATE > DATEADD (MONTH, -12, GETDATE ())
	AND PAT_ENC.APPT_STATUS_C IN ( 2, 6 )
;


IF OBJECT_ID ('tempdb..#Attribution2') IS NOT NULL
	DROP TABLE #Attribution2
	;
SELECT
	a1.PAT_ID
	,a1.STATE
	,a1.CITY
	,a1.SITE
	,a1.LOS
	,a1.VISIT_PROVIDER_TYPE
	,ROW_NUMBER () OVER (PARTITION BY a1.PAT_ID ORDER BY a1.LAST_OFFICE_VISIT DESC) AS ROW_NUM_DESC

INTO #Attribution2

FROM
	#Attribution1 a1

WHERE
	a1.LOS = 'DENTAL'
;


IF OBJECT_ID ('tempdb..#Attribution3') IS NOT NULL
	DROP TABLE #Attribution3
	;
SELECT
	a2.PAT_ID
	,a2.LOS
	,a2.CITY
	,a2.STATE
	,a2.VISIT_PROVIDER_TYPE

INTO #Attribution3

FROM
	#Attribution2 a2
	INNER JOIN CLARITY.dbo.EPISODE_VIEW EPISODE ON EPISODE.PAT_LINK_ID = a2.PAT_ID
	INNER JOIN CLARITY.dbo.ORDER_PROC_VIEW AS ORDER_PROC ON a2.PAT_ID = ORDER_PROC.PAT_ID
	INNER JOIN CLARITY.dbo.CLARITY_EAP AS CLARITY_EAP ON ORDER_PROC.PROC_ID = CLARITY_EAP.PROC_ID
	INNER JOIN CLARITY.dbo.PAT_ENC_VIEW AS PAT_ENC ON ORDER_PROC.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID

WHERE
	a2.ROW_NUM_DESC = 1
	AND EPISODE.SUM_BLK_TYPE_ID = 45
	AND EPISODE.STATUS_C = 1
	AND DATEDIFF (MONTH, PAT_ENC.CONTACT_DATE, GETDATE ()) <= 12
	AND CLARITY_EAP.PROC_CODE IN ( 'TX130', 'TX630', 'D0120', 'D0150', 'D0180', 'D0160', 'D0170', 'D0190' )
;


IF OBJECT_ID('tempdb..#b') IS NOT NULL
    DROP TABLE #b;
;

WITH ProbingEncounters AS (
    SELECT
        pev.PAT_ID,
        pev.PAT_ENC_CSN_ID,
        pev.CONTACT_DATE,
        pev.VISIT_PROV_ID           AS Visit_Prov_ID,
        ser.PROV_NAME               AS Visit_Prov_Name,
        ROW_NUMBER() OVER (
            PARTITION BY pev.PAT_ID
            ORDER BY pev.CONTACT_DATE DESC, pev.PAT_ENC_CSN_ID DESC
        ) AS rn
    FROM CLARITY.dbo.DENTAL_TOOTH_HX_VIEW      AS dthv
    INNER JOIN CLARITY.dbo.DENTAL_PROBEDEPTH_HX AS dph
        ON dph.FINDING_ID = dthv.FINDING_ID       -- probing confirmed
    INNER JOIN CLARITY.dbo.PAT_ENC_VIEW         AS pev
        ON dthv.DENTAL_PATIENT_CSN = pev.PAT_ENC_CSN_ID
    INNER JOIN CLARITY.dbo.CLARITY_SER_VIEW     AS ser
        ON pev.VISIT_PROV_ID = ser.PROV_ID
    WHERE pev.CONTACT_DATE > DATEADD(MONTH, -13, GETDATE())
)
SELECT
    PAT_ID,
    Visit_Prov_ID,
    Visit_Prov_Name
INTO #b
FROM ProbingEncounters
WHERE rn = 1; 

SELECT
	IDENTITY_ID.IDENTITY_ID
	,PATIENT.PAT_NAME
	,CASE
		WHEN b.PAT_ID IS NOT NULL THEN 1
		ELSE 0
	END AS One_Plus_Prophy
	,CASE
		WHEN b.PAT_ID IS NOT NULL THEN 'MET'
		ELSE 'NOT MET'
	END AS MET_YN
	,a3.STATE
	,a3.CITY
	,a3.VISIT_PROVIDER_TYPE
	,b.Visit_Prov_ID   AS [Visit Provider ID]
	,b.Visit_Prov_Name AS [Visit Provider Name]
	,PATIENT.HOME_PHONE
	,PATIENT.WORK_PHONE
	,MAX (OTHER_COMMUNCTN.OTHER_COMMUNIC_NUM) CELL_PHONE
	,GETDATE () AS UPDATE_DTTM

FROM
	#Attribution3 a3
	LEFT JOIN #b b ON b.PAT_ID = a3.PAT_ID
	INNER JOIN CLARITY.dbo.PATIENT_VIEW AS PATIENT ON a3.PAT_ID = PATIENT.PAT_ID
	INNER JOIN CLARITY.dbo.PATIENT_4 AS PATIENT_4 ON PATIENT.PAT_ID = PATIENT_4.PAT_ID
	LEFT JOIN CLARITY.dbo.OTHER_COMMUNCTN AS OTHER_COMMUNCTN ON PATIENT.PAT_ID = OTHER_COMMUNCTN.PAT_ID
																AND OTHER_COMMUNCTN.OTHER_COMMUNIC_C = 1
	INNER JOIN CLARITY.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID ON PATIENT.PAT_ID = IDENTITY_ID.PAT_ID

WHERE
	PATIENT_4.PAT_LIVING_STAT_C = 1
	AND PATIENT.PAT_ID NOT IN ( SELECT DISTINCT #exclusion.PAT_ID FROM #exclusion )

GROUP BY
	b.PAT_ID
	,IDENTITY_ID.IDENTITY_ID
	,PATIENT.PAT_NAME
	,b.PAT_ID
	,b.Visit_Prov_ID  ,
	b.Visit_Prov_Name 
	,a3.CITY
	,a3.VISIT_PROVIDER_TYPE
	,a3.STATE
	,PATIENT.HOME_PHONE
	,PATIENT.WORK_PHONE

;

DROP TABLE #excl;
DROP TABLE #exclusion;