/* ANL-MKE-SVR-100 */

SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

SELECT id.IDENTITY_ID,
       p.PAT_NAME,
       CAST(p.BIRTH_DATE AS DATE) AS BIRTH_DATE,
       (DATEDIFF(m, p.BIRTH_DATE, GETDATE()) / 12) AGE,
       CAST(pev.CONTACT_DATE AS DATE) AS CONTACT_DATE,
       DATENAME(DW, pev.CONTACT_DATE) 'DAY',
       pev.APPT_STATUS_C,
       pev.APPT_TIME APPT_DATETIME,
       LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) APPOINTMENT_TIME,
       CASE 
           WHEN LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) LIKE '%:15' THEN LEFT(DATEADD(MINUTE, -15, (CONVERT(TIME(0), LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)))), 5)
           WHEN LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) LIKE '%:45' THEN LEFT(DATEADD(MINUTE, -15, (CONVERT(TIME(0), LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)))), 5)
           WHEN LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) LIKE '%:40' THEN LEFT(DATEADD(MINUTE, -10, (CONVERT(TIME(0), LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)))), 5)
           WHEN LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) LIKE '%:20' THEN LEFT(DATEADD(MINUTE, -20, (CONVERT(TIME(0), LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)))), 5)
           WHEN LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) LIKE '%:50' THEN LEFT(DATEADD(MINUTE, +10, (CONVERT(TIME(0), LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)))), 5)
           WHEN LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5) LIKE '%:10' THEN LEFT(DATEADD(MINUTE, -10, (CONVERT(TIME(0), LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)))), 5)
           ELSE LEFT(DATEADD(MINUTE, 0, (CONVERT(TIME(0), pev.APPT_TIME))), 5)
       END AS 'APPT_TIME',
       CASE 
            WHEN pev.APPT_STATUS_C IN ( 4, 5, 7, 13 ) THEN 'NO SHOW' --No Show (if course), Late Cancel, Patient to Late to be Seen, and Left Without Being Seen.
       END AS 'NO SHOW',
       CASE 
            WHEN pev.APPT_STATUS_C NOT IN ( 4, 5, 7, 13 ) THEN 'COMPLETE'
       END AS 'COMPLETE',
       CASE 
            WHEN pev.APPT_STATUS_C IN ( 4, 5, 7, 13 ) THEN 'NO SHOW'
            ELSE 'COMPLETE'
       END AS 'APPOINTMENT STATUS',
       pev.APPT_PRC_ID,
       ser.PROV_NAME,
       ser.PROV_TYPE,
       ser.PROVIDER_TYPE_C,
       dep.DEPARTMENT_NAME,
       CASE 
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'MD' THEN 'MEDICAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'DT' THEN 'DENTAL'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) IN ( 'MH', 'BH', 'PY', 'AD' ) THEN 'BEHAVIORAL'
           ELSE 'ERROR'
       END AS 'LOS',
       SUBSTRING(dep.DEPT_ABBREVIATION, 3, 2) 'STATE',
       zs.NAME SEX,
       zpr.NAME RACE,
       CASE 
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
           WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
		   WHEN SUBSTRING(dep.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
           ELSE 'ERROR'
       END AS CITY,
     p.ZIP,
       prc.PRC_NAME 'APPT TYPE'
FROM CLARITY.dbo.PATIENT_VIEW p
    LEFT JOIN CLARITY.dbo.PAT_ENC_VIEW pev ON p.PAT_ID = pev.PAT_ID
                                              AND pev.APPT_STATUS_C NOT IN ( 1, 3, 8, 10, 12 ) -- Excludes Scheduled, Canceled, Non-encounter, pt not cooperative and Void
    --AND pev.APPT_PRC_ID NOT IN (118, 119, 120, 152, 428, 506, 50) --Excludes AODA group and non-important appts
    INNER JOIN CLARITY.dbo.CLARITY_PRC prc ON pev.APPT_PRC_ID = prc.PRC_ID
    INNER JOIN CLARITY.dbo.IDENTITY_ID_VIEW id ON pev.PAT_ID = id.PAT_ID
    LEFT JOIN CLARITY.dbo.CLARITY_SER_VIEW ser ON pev.VISIT_PROV_ID = ser.PROV_ID
    LEFT JOIN CLARITY.dbo.CLARITY_DEP_VIEW dep ON pev.DEPARTMENT_ID = dep.DEPARTMENT_ID
    LEFT JOIN CLARITY.dbo.ZC_SEX zs ON p.SEX_C = zs.RCPT_MEM_SEX_C
    LEFT JOIN CLARITY.dbo.PATIENT_RACE pr ON p.PAT_ID = pr.PAT_ID
                                             AND pr.LINE = 1
    LEFT JOIN CLARITY.dbo.ZC_PATIENT_RACE zpr ON pr.PATIENT_RACE_C = zpr.PATIENT_RACE_C
WHERE pev.CONTACT_DATE > DATEADD(MONTH, -12, GETDATE())
      AND ser.PROVIDER_TYPE_C IN ( 117, 113, 129, 1, 136, 117, 9, 110, 119, 10, 134, 164, 108, 177, 6 ) --Only billing-level providers
      AND SUBSTRING(dep.DEPT_ABBREVIATION, 9, 2) = 'AD';