SET NOCOUNT ON;
SET ANSI_WARNINGS OFF;

IF OBJECT_ID('tempdb..#insurance_information') IS NOT NULL DROP TABLE #insurance_information;
SELECT 
	cml.COVERAGE_ID
	,cml.PAT_ID
	,vcp.PAYOR_ID
	,vcp.PAYOR_NAME
	,vcp.BENEFIT_PLAN_ID
	,vcp.BENEFIT_PLAN_NAME AS INSURANCE_BENEFIT_NAME
	,vcp.FIN_CLASS_C
	,vcp.FIN_CLASS_NAME AS FINANCIAL_CLASS_NAME
	,vcp.EFF_DATE
	,ROW_NUMBER() OVER (PARTITION BY cml.PAT_ID ORDER BY cml.MEM_EFF_FROM_DATE DESC) AS ROW_NUM_DESC

INTO #insurance_information

FROM 
	Clarity.dbo.V_COVERAGE_PAYOR_PLAN vcp
    INNER JOIN Clarity.dbo.COVERAGE_MEM_LIST cml ON vcp.COVERAGE_ID = cml.COVERAGE_ID

WHERE 
	cml.MEM_EFF_TO_DATE IS NULL /* Currently enrolled */
    AND cml.MEM_COVERED_YN = 'Y' /* Covered patients */

ORDER BY 
	cml.PAT_ID
    ,cml.MEM_EFF_FROM_DATE

;

IF OBJECT_ID('tempdb..#SEX') IS NOT NULL 
DROP TABLE #SEX;

SELECT 
	p.PAT_ID
	,CASE WHEN p4.SEX_ASGN_AT_BIRTH_C IN ( 1, 2 ) THEN zb.NAME
		WHEN p4.GENDER_IDENTITY_C IN ( 1, 4 ) THEN 'Female'
		WHEN p4.GENDER_IDENTITY_C IN ( 2, 3 ) THEN 'Male'
		WHEN (p4.GENDER_IDENTITY_C IS NULL OR p4.GENDER_IDENTITY_C NOT IN ( 1, 2, 3, 4 ))
			AND p.SEX_C IN ( 1, 5 ) THEN 'Female'
		WHEN (p4.GENDER_IDENTITY_C IS NULL OR p4.GENDER_IDENTITY_C NOT IN ( 1, 2, 3, 4 ))
			AND p.SEX_C IN ( 2, 4 ) THEN 'Male'
		ELSE 'UNKNOWN'
	END SEX_AT_BIRTH

INTO #SEX

FROM 
	Clarity.dbo.PATIENT_4 p4
    LEFT JOIN Clarity.dbo.ZC_SEX_ASGN_AT_BIRTH zb ON zb.SEX_ASGN_AT_BIRTH_C = p4.SEX_ASGN_AT_BIRTH_C
    INNER JOIN Clarity.dbo.PATIENT_VIEW p ON p.PAT_ID = p4.PAT_ID
    INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW id ON id.PAT_ID = p4.PAT_ID

WHERE 
	id.IDENTITY_TYPE_ID = 64
;


IF OBJECT_ID('tempdb..#last_injection_info') IS NOT NULL 
DROP TABLE #last_injection_info;

SELECT 
	ORDER_MED.PAT_ID
	,MAR_ADMIN_INFO.TAKEN_TIME AS LAST_INJECTION_DATE
	,CLARITY_DEP.DEPARTMENT_NAME
	,CLARITY_MEDICATION.NAME AS MEDICATION_NAME
	,ZC_ORDER_CLASS.NAME AS MEDICATION_ORDER_CLASS
	,ROW_NUMBER() OVER (PARTITION BY ORDER_MED.PAT_ID ORDER BY MAR_ADMIN_INFO.TAKEN_TIME DESC) AS RN_DESC

INTO #last_injection_info

FROM 
	CLARITY.dbo.ORDER_MED_VIEW AS ORDER_MED
    INNER JOIN CLARITY.dbo.CLARITY_MEDICATION AS CLARITY_MEDICATION ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID
    INNER JOIN CLARITY.dbo.MAR_ADMIN_INFO_VIEW AS MAR_ADMIN_INFO ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID
    INNER JOIN CLARITY.dbo.ZC_ORDER_CLASS AS ZC_ORDER_CLASS ON ZC_ORDER_CLASS.ORDER_CLASS_C = ORDER_MED.ORDER_CLASS_C
    INNER JOIN CLARITY.dbo.PAT_ENC_VIEW AS PAT_ENC ON ORDER_MED.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID
    INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID

WHERE 
	CLARITY_MEDICATION.GENERIC_NAME LIKE '%cabotegravir%'
    AND MAR_ADMIN_INFO.MAR_ACTION_C = 1 -- Given
	  
; 

IF OBJECT_ID('tempdb..#final') IS NOT NULL 
DROP TABLE #final;
WITH
    LAST_INJECTION_DATE AS (
        SELECT 
			li.PAT_ID
           ,li.LAST_INJECTION_DATE
           ,li.DEPARTMENT_NAME
           ,li.MEDICATION_NAME
           ,li.MEDICATION_ORDER_CLASS

        FROM 
			#last_injection_info li

        WHERE 
			li.RN_DESC = 1
    ),
    NEXT_INJECTION_DATE AS (
        SELECT 
			ORDER_MED.PAT_ID
           , MAR_ADMIN_INFO.TAKEN_TIME AS NEXT_INJECTION_DATE
            ,CLARITY_MEDICATION.NAME AS MEDICATION_NAME
            ,ZC_ORDER_CLASS.NAME AS MEDICATION_ORDER_CLASS
            ,CLARITY_SER.PROV_NAME AS NEXT_INJECTION_VISIT_PROVIDER
            ,ROW_NUMBER() OVER (PARTITION BY ORDER_MED.PAT_ID ORDER BY MAR_ADMIN_INFO.TAKEN_TIME) AS RN_ASC

        FROM 
			CLARITY.dbo.ORDER_MED_VIEW AS ORDER_MED
            INNER JOIN CLARITY.dbo.CLARITY_MEDICATION AS CLARITY_MEDICATION ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID
            INNER JOIN CLARITY.dbo.MAR_ADMIN_INFO_VIEW AS MAR_ADMIN_INFO ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID
            INNER JOIN CLARITY.dbo.ZC_ORDER_CLASS AS ZC_ORDER_CLASS ON ZC_ORDER_CLASS.ORDER_CLASS_C = ORDER_MED.ORDER_CLASS_C
            INNER JOIN Clarity.dbo.PAT_ENC_VIEW AS PAT_ENC ON MAR_ADMIN_INFO.MAR_ENC_CSN = PAT_ENC.PAT_ENC_CSN_ID
            INNER JOIN Clarity.dbo.CLARITY_SER_VIEW AS CLARITY_SER ON PAT_ENC.VISIT_PROV_ID = CLARITY_SER.PROV_ID

        WHERE 
			CLARITY_MEDICATION.GENERIC_NAME LIKE '%cabotegravir%'
            AND MAR_ADMIN_INFO.MAR_ACTION_C = 100 -- Due
            AND MAR_ADMIN_INFO.TAKEN_TIME >= CURRENT_TIMESTAMP
    ),
    NEXT_MEDICAL_APPOINTMENT AS (
        SELECT 
			PAT_ENC.PAT_ID
            ,PAT_ENC.CONTACT_DATE AS NEXT_ANY_APPOINTMENT
            ,CLARITY_SER.PROV_NAME AS NEXT_APPT_PROVIDER
            ,ROW_NUMBER() OVER (PARTITION BY PAT_ENC.PAT_ID ORDER BY PAT_ENC.CONTACT_DATE ASC) AS RN_ASC

        FROM 
			CLARITY.dbo.PAT_ENC_VIEW AS PAT_ENC
            INNER JOIN CLARITY.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID
            INNER JOIN CLARITY.dbo.CLARITY_SER_VIEW AS CLARITY_SER ON PAT_ENC.VISIT_PROV_ID = CLARITY_SER.PROV_ID

        WHERE 
			PAT_ENC.APPT_STATUS_C = 1 -- Scheduled
    ),
    episode_by_encounter AS (
        SELECT DISTINCT 
			PAT_ENC.PAT_ENC_CSN_ID
            ,CASE WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) = 'WI' THEN 'WISCONSIN'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) = 'MO' THEN 'MISSOURI'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) = 'CO' THEN 'COLORADO'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2) = 'TX' THEN 'TEXAS'
                ELSE SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 3, 2)
            END AS STATE
           ,CASE WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'MK' THEN 'MILWAUKEE'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'KN' THEN 'KENOSHA'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'GB' THEN 'GREEN BAY'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'WS' THEN 'WAUSAU'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'AP' THEN 'APPLETON'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'EC' THEN 'EAU CLAIRE'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'LC' THEN 'LACROSSE'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'MD' THEN 'MADISON'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'BL' THEN 'BELOIT'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'BI' THEN 'BILLING'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'SL' THEN 'ST LOUIS'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'KC' THEN 'KANSAS CITY'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'DN' THEN 'DENVER'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'AS' THEN 'AUSTIN'
                WHEN SUBSTRING(CLARITY_DEP.DEPT_ABBREVIATION, 5, 2) = 'CG' THEN 'CHICAGO'
                ELSE 'ERROR'
            END AS CITY

        FROM 
			Clarity.dbo.PAT_ENC_VIEW AS PAT_ENC
            INNER JOIN CLARITY.dbo.EPISODE_LINK_VIEW AS EPISODE_LINK ON PAT_ENC.PAT_ENC_CSN_ID = EPISODE_LINK.PAT_ENC_CSN_ID
            INNER JOIN CLARITY.dbo.EPISODE_VIEW AS EPISODE ON EPISODE_LINK.EPISODE_ID = EPISODE.EPISODE_ID
            INNER JOIN Clarity.dbo.CLARITY_DEP_VIEW AS CLARITY_DEP ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID

        WHERE 
			EPISODE.SUM_BLK_TYPE_ID = 261
            AND EPISODE.STATUS_C = 1
    ),
    episode_by_patient AS (
        SELECT DISTINCT 
			PATIENT.PAT_ID

        FROM 
			Clarity.dbo.EPISODE_VIEW AS EPISODE
            INNER JOIN Clarity.dbo.PAT_EPISODE_VIEW AS PAT_EPISODE ON EPISODE.EPISODE_ID = PAT_EPISODE.EPISODE_ID
            INNER JOIN Clarity.dbo.PATIENT_VIEW AS PATIENT ON PAT_EPISODE.PAT_ID = PATIENT.PAT_ID

        WHERE 
			EPISODE.SUM_BLK_TYPE_ID = 261
            AND EPISODE.STATUS_C = 1
    ),
    episode_info AS (
        SELECT 
			episode_by_patient.PAT_ID
           ,episode_by_encounter.PAT_ENC_CSN_ID
           ,COALESCE(episode_by_encounter.STATE, 'zzz') AS STATE
           ,COALESCE(episode_by_encounter.CITY, 'zzz') AS CITY

        FROM 
			Clarity.dbo.PAT_ENC_VIEW AS PAT_ENC
            LEFT JOIN episode_by_encounter ON PAT_ENC.PAT_ENC_CSN_ID = episode_by_encounter.PAT_ENC_CSN_ID
            LEFT JOIN episode_by_patient ON PAT_ENC.PAT_ID = episode_by_patient.PAT_ID

        WHERE 
			(episode_by_encounter.PAT_ENC_CSN_ID IS NOT NULL
               OR episode_by_patient.PAT_ID IS NOT NULL)

        GROUP BY 
			episode_by_patient.PAT_ID,
            episode_by_encounter.PAT_ENC_CSN_ID,
            episode_by_encounter.STATE,
            episode_by_encounter.CITY
    )
	SELECT 
		IDENTITY_ID.IDENTITY_ID AS MRN
		,IDENTITY_ID.PAT_ID
		,PATIENT.PAT_NAME
		,s.SEX_AT_BIRTH
		,episode_info.STATE
		,episode_info.CITY
		,DATEDIFF(YEAR, PATIENT.BIRTH_DATE, CURRENT_TIMESTAMP) AS AGE
		,i.FINANCIAL_CLASS_NAME
		,CAST(LAST_INJECTION_DATE.LAST_INJECTION_DATE AS DATE) AS LAST_INJECTION_DATE
		,LAST_INJECTION_DATE.DEPARTMENT_NAME AS LAST_INJECTION_DEPARTMENT_NAME
		,CAST(nvis.CONTACT_DATE AS DATE) AS NEXT_INJECTION_DATE
		,nvis.PROV_NAME NEXT_INJECTION_VISIT_PROVIDER
		,CAST(NEXT_MEDICAL_APPOINTMENT.NEXT_ANY_APPOINTMENT AS DATE) AS NEXT_ANY_APPOINTMENT
		,NEXT_MEDICAL_APPOINTMENT.NEXT_APPT_PROVIDER
		,CASE WHEN ZC_BPA_TRIGGER_FYI.BPA_TRIGGER_FYI_C = '640036' THEN '8 week'
			WHEN ZC_BPA_TRIGGER_FYI.BPA_TRIGGER_FYI_C = '640037' THEN '8 week'
			ELSE '4 week'
		END AS CABENUVA_TYPE
		,CASE WHEN ZC_BPA_TRIGGER_FYI.BPA_TRIGGER_FYI_C = '640037' THEN 'Medical Billing'
			WHEN ZC_BPA_TRIGGER_FYI.BPA_TRIGGER_FYI_C = '640039' THEN 'Medical Billing'
			ELSE 'Pharmacy Billing'
		END AS BENEFIT
		,CURRENT_TIMESTAMP AS UPDATE_DTTM
		,ROW_NUMBER() OVER (PARTITION BY IDENTITY_ID.IDENTITY_ID	ORDER BY episode_info.STATE, episode_info.CITY ASC) AS ROW_NUM_ASC

	INTO #final

	FROM 
		Clarity.dbo.PATIENT_VIEW AS PATIENT
		INNER JOIN episode_info ON PATIENT.PAT_ID = episode_info.PAT_ID
		INNER JOIN Clarity.dbo.IDENTITY_ID_VIEW AS IDENTITY_ID ON episode_info.PAT_ID = IDENTITY_ID.PAT_ID
		INNER JOIN #SEX s ON PATIENT.PAT_ID = s.PAT_ID
		LEFT JOIN CLARITY.dbo.PATIENT_FYI_FLAGS_VIEW AS PATIENT_FYI_FLAGS ON episode_info.PAT_ID = PATIENT_FYI_FLAGS.PATIENT_ID
											AND PATIENT_FYI_FLAGS.PAT_FLAG_TYPE_C IN ( '640036', '640037', '640038', '640039' )
											AND PATIENT_FYI_FLAGS.ACTIVE_C = 1
		LEFT JOIN CLARITY.dbo.ZC_BPA_TRIGGER_FYI AS ZC_BPA_TRIGGER_FYI ON PATIENT_FYI_FLAGS.PAT_FLAG_TYPE_C = ZC_BPA_TRIGGER_FYI.BPA_TRIGGER_FYI_C
		LEFT JOIN #insurance_information i ON episode_info.PAT_ID = i.PAT_ID
											AND i.ROW_NUM_DESC = 1
		LEFT JOIN LAST_INJECTION_DATE ON episode_info.PAT_ID = LAST_INJECTION_DATE.PAT_ID
		LEFT JOIN NEXT_MEDICAL_APPOINTMENT ON episode_info.PAT_ID = NEXT_MEDICAL_APPOINTMENT.PAT_ID
											AND NEXT_MEDICAL_APPOINTMENT.RN_ASC = 1
		LEFT JOIN NEXT_INJECTION_DATE ON episode_info.PAT_ID = NEXT_INJECTION_DATE.PAT_ID
										   AND NEXT_INJECTION_DATE.RN_ASC = 1
		LEFT JOIN
			(SELECT 
				pev.PAT_ID
				,pev.CONTACT_DATE
				,ser.PROV_NAME
				,ROW_NUMBER() OVER (PARTITION BY pev.PAT_ID ORDER BY pev.CONTACT_DATE ASC) AS ROW_NUM_ASC

			FROM 
				Clarity.dbo.PAT_ENC_VIEW pev
				INNER JOIN Clarity.dbo.EPISODE_LINK_VIEW elv ON elv.PAT_ENC_CSN_ID = pev.PAT_ENC_CSN_ID
				INNER JOIN Clarity.dbo.EPISODE_ALL e  ON e.EPISODE_ID = elv.EPISODE_ID	
				INNER JOIN Clarity.dbo.CLARITY_PRC prc ON pev.APPT_PRC_ID =prc.PRC_ID
				INNER JOIN Clarity.dbo.CLARITY_SER_VIEW ser ON pev.VISIT_PROV_ID = ser.PROV_ID

			WHERE
				pev.APPT_STATUS_C = 1
				AND e.SUM_BLK_TYPE_ID = 261 --CAM
				AND prc.PRC_ID = '123' --INJECTION
				AND pev.CONTACT_DATE > GETDATE()-1
			) nvis ON nvis.PAT_ID = PATIENT.PAT_ID
						AND nvis.ROW_NUM_ASC = 1 --Next Visit

	WHERE 
		PATIENT.CUR_PCP_PROV_ID IS NOT NULL

;


SELECT 
	f.MRN
	,f.PAT_NAME
	,f.SEX_AT_BIRTH
	,CASE 
		WHEN f.STATE = 'zzz' THEN NULL
		ELSE f.STATE
	END AS STATE
	,CASE 
		WHEN f.CITY = 'zzz' THEN NULL
		ELSE f.CITY
	END AS CITY
	,f.AGE
	,f.FINANCIAL_CLASS_NAME
	,f.LAST_INJECTION_DATE
	,f.LAST_INJECTION_DEPARTMENT_NAME
	,f.NEXT_INJECTION_DATE
	,f.NEXT_INJECTION_VISIT_PROVIDER
	,f.NEXT_ANY_APPOINTMENT
	,f.NEXT_APPT_PROVIDER
	,f.CABENUVA_TYPE
	,f.BENEFIT
	,f.UPDATE_DTTM

FROM 
	#final f

WHERE 
	f.ROW_NUM_ASC = 1
    AND f.MRN <> '640041669' -- Test patient

ORDER BY 
	f.MRN
;

DROP TABLE #final
DROP TABLE #SEX
DROP TABLE #insurance_information
DROP TABLE #last_injection_info